version: "3.8"

# This is an example of a multi-instance setup. To use it copy the .env.multi.example to .env and adjust the values.
# Add /etc/hosts:
# 127.0.0.1 augustin1 augustin2 keycloak keycloak2 backend 

# After starting the containers, the second keyclaok has to be imported manually, the clients can be imported from
# docker/keycloak-multi/

services:
  augustin-frontend:
    container_name: augustin-frontend
    build:
      context: ./docker/augustin-frontend
    volumes:
      - ./docker/augustin-frontend/docker/entrypoint.sh:/docker-entrypoint.d/10-entrypoint.sh
    ports:
      - "8060:80"
    environment:
      VITE_API_URL: ${BACKEND_HOST}
      VITE_KEYCLOAK_URL: ${KEYCLOAK_HOST}
      VITE_AUGUSTIN_COVER: ${AUGUSTIN_COVER}
      VITE_AGB_URL: ${AGB_URL}
    depends_on:
      - augustin_backend1
      - augustin_backend2
  augustin_backend1:
    container_name: augustin_backend1
    env_file:
      - .env
    build:
      context: .
    volumes:
      - ./app:/app
      - ./email_templates:/app/templates
    command: >
      sh -c "tern migrate --migrations ./migrations --config
      ./migrations/tern.conf && tern migrate --migrations ./migrations --config
      ./migrations/tern_test.conf  && go run main.go"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_HOST_TEST: ${DB_HOST_TEST}
      DB_PORT_TEST: ${DB_PORT_TEST}
      DEVELOPMENT: true
      FRONTEND_URL: ${FRONTEND_URL}
      VIVA_WALLET_SOURCE_CODE: ${VIVA_WALLET_SOURCE_CODE}
      VIVA_WALLET_SMART_CHECKOUT_CLIENT_ID: ${VIVA_WALLET_SMART_CHECKOUT_CLIENT_ID}
      VIVA_WALLET_SMART_CHECKOUT_CLIENT_KEY: ${VIVA_WALLET_SMART_CHECKOUT_CLIENT_KEY}
      VIVA_WALLET_VERIFICATION_KEY: ${VIVA_WALLET_VERIFICATION_KEY}
      VIVA_WALLET_API_URL: ${VIVA_WALLET_API_URL}
      VIVA_WALLET_ACCOUNTS_URL: ${VIVA_WALLET_ACCOUNTS_URL}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_ADDRESS: ${SMTP_SENDER_ADDRESS}
      BACKEND_HOST: ${BACKEND_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      augustin-db:
        condition: service_healthy
    links:
      - augustin-db
      - augustin-db-test
      - keycloak
    ports:
      - "3001:3000"
    healthcheck:
      test: curl -f "$BACKEND_HOST/api/hello/" || exit 1
      interval: 60s   # check every minute
      timeout: 20s    # maximum time to wait for a response
      retries: 3      # number of retries before considering the container unhealthy
      start_period: 2m
  augustin_backend2:
    container_name: augustin_backend2
    env_file:
      - .env
    build:
      context: .
    volumes:
      - ./app:/app
      - ./email_templates:/app/templates
    command: >
      sh -c "tern migrate --migrations ./migrations --config
      ./migrations/tern.conf && go run main.go"
    environment:
      DB_USER: ${DB_USER2}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME2}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_HOST_TEST: ${DB_HOST_TEST}
      DB_PORT_TEST: ${DB_PORT_TEST}
      DEVELOPMENT: false
      FRONTEND_URL: ${FRONTEND_URL}
      VIVA_WALLET_SOURCE_CODE: ${VIVA_WALLET_SOURCE_CODE}
      VIVA_WALLET_SMART_CHECKOUT_CLIENT_ID: ${VIVA_WALLET_SMART_CHECKOUT_CLIENT_ID}
      VIVA_WALLET_SMART_CHECKOUT_CLIENT_KEY: ${VIVA_WALLET_SMART_CHECKOUT_CLIENT_KEY}
      VIVA_WALLET_VERIFICATION_KEY: ${VIVA_WALLET_VERIFICATION_KEY}
      VIVA_WALLET_API_URL: ${VIVA_WALLET_API_URL}
      VIVA_WALLET_ACCOUNTS_URL: ${VIVA_WALLET_ACCOUNTS_URL}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_ADDRESS: ${SMTP_SENDER_ADDRESS}
      BACKEND_HOST: ${BACKEND_HOST2}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM2}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET2}
    depends_on:
      augustin-db:
        condition: service_healthy
    links:
      - augustin-db
      - augustin-db-test
      - keycloak
    ports:
      - "3002:3000"
    healthcheck:
      test: curl -f "$BACKEND_HOST/api/hello/" || exit 1
      interval: 60s   # check every minute
      timeout: 20s    # maximum time to wait for a response
      retries: 3      # number of retries before considering the container unhealthy
      start_period: 2m
  augustin-db:
    container_name: augustin-db
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME}, ${DB_NAME2}
      TZ: "UTC"
      PGTZ: "UTC"
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  api-reverse-proxy:
    image: nginx:stable
    container_name: api-reverse-proxy
    volumes:
      - ./docker/api-reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  augustin-db-test:
    container_name: augustin-db-test
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: "UTC"
      PGTZ: "UTC"
    command: -p ${DB_PORT_TEST}
    ports:
      - "${DB_PORT_TEST}:${DB_PORT_TEST}"
    volumes:
      - dbdata-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build: ./docker/keycloak
    container_name: augustin-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_HOST}
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_HOSTNAME_URL: ${KEYCLOAK_HOST}
      KC_HOSTNAME_ADMIN_URL: ${KEYCLOAK_HOST}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/realms/master"]
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/export:/tmp/export
      - ./docker/keycloak/themes/augustin:/opt/keycloak/themes/augustin:ro

    command: start-dev --import-realm
    ports:
      - "8080:8080"
volumes:
  dbdata:
  wp_data:
  wp_db_data:
  dbdata-test:
