version: "3.8"

services:
  augustin-frontend:
    build:
      context: ./docker/augustin-frontend
    image: dkia/augustin-frontend
    ports:
      - "7002:80"
    environment:
      VITE_API_URL: ${BACKEND_HOST}
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
    depends_on:
      - augustin-backend
  augustin-backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: dkia/augustin-backend
    volumes:
      - /dockerstorage/convive/augustin/data/backend/img:/app/img
      - /dockerstorage/convive/augustin/data/backend/pdf:/app/pdf
      - /dockerstorage/convive/augustin/data/backend/email_templates:/app/templates

    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_HOST_TEST: ${DB_HOST_TEST}
      DB_PORT_TEST: ${DB_PORT_TEST}
      DEVELOPMENT: ${DEVELOPMENT}
      FRONTEND_URL: ${FRONTEND_URL}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - augustin-db
    links:
      - augustin-db
      - keycloak
    ports:
      - "7001:3000"
  augustin-db:
    image: postgres:15.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: "UTC"
      PGTZ: "UTC"
    command: -p ${DB_PORT}
    volumes:
      - /dockerstorage/convive/augustin-backend/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "7005:5432"
  pgbackups-augustin-db:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
        - /dockerstorage/convive/augustin-db-backups:/backups
    depends_on:
      - augustin-db
    environment:
        - POSTGRES_HOST=${DB_BACKUP_HOST}
        - POSTGRES_PORT=7005
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
        - SCHEDULE=@every 3m
        - BACKUP_KEEP_MINS=1900
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080

  keycloak:
    build:
      context: ./docker/keycloak
      dockerfile: ./Dockerfile.production
    image: dkia/augustin-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_HOST}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_URL_PORT: ${KEYCLOAK_DB_PORT}
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_HOSTNAME_URL: ${KEYCLOAK_HOST}
      KC_HOSTNAME_ADMIN_URL: ${KEYCLOAK_HOST}
    depends_on:
      - keycloak-db
    volumes:
      - /dockerstorage/convive/augustin-backend/docker/keycloak/import:/opt/keycloak/data/import
      - /dockerstorage/convive/augustin-backend/docker/keycloak/export:/tmp/export
      - /dockerstorage/convive/augustin-backend/docker/keycloak/themes/augustin:/opt/keycloak/themes/augustin:ro

    ports:
      - "7000:8080"
  keycloak-db:
    image: postgres:14-alpine
    volumes:
      - /dockerstorage/convive/augustin-backend/keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
  wordpress-db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - /dockerstorage/convive/augustin-backend/wp_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
  wordpress:
    image: wordpress:latest
    volumes:
      - /dockerstorage/convive/augustin-backend/wp_data:/var/www/html
      - /dockerstorage/convive/augustin-backend/docker/wordpress/plugins/augustin-wp-papers:/var/www/html/wp-content/plugins/augustin-wp-papers
      - /dockerstorage/convive/augustin-backend/docker/wordpress/themes/augustin-wp-theme:/var/www/html/wp-content/themes/augustin-wp-theme
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - AUGUSTIN_PLUGIN_URL=${AUGUSTIN_PARSER_URL}
    depends_on:
      - wordpress-db
      - keycloak
    ports:
      - "7004:80"
  wpcli:
    image: wordpress:cli
    user: 0:0
    command: >
      sh -c " chmod +x /wpcli/entrypoint.sh && /wpcli/entrypoint.sh && tail -f
      /dev/null"
    volumes:
      - /dockerstorage/convive/augustin-backend/wp_data:/var/www/html
      - /dockerstorage/convive/augustin-backend/docker/wordpress/plugins/augustin-wp-papers:/var/www/html/wp-content/plugins/augustin-wp-papers
      - /dockerstorage/convive/augustin-backend/docker/wordpress/themes/augustin-wp-theme:/var/www/html/wp-content/themes/augustin-wp-theme
      - /dockerstorage/convive/augustin-backend/docker/wpcli/:/wpcli/

    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    depends_on:
      - wordpress-db
      - wordpress
    links:
      - wordpress-db
  parser:
    build:
      context: ./docker/augustin-plugin
    image: dkia/augustin-parser
    ports:
      - "7003:8000"
    volumes:
      - /dockerstorage/convive/augustin-backend/docker/augustin-plugin-data/sample_data:/sample_data
      - /dockerstorage/convive/augustin-backend/docker/augustin-plugin-data/pdf-files:/pdf-files
      - /dockerstorage/convive/augustin-backend/docker/augustin-plugin/:/app
    environment:
      - AUGUSTIN_PLUGIN_URL=${AUGUSTIN_PLUGIN_URL}
      - AUGUSTIN_PLUGIN_PATH=/sample_data/
      - AUGUSTIN_PLUGIN_SAVE_PATH=/pdf-files/
      - WP_API_USER=api_user
    depends_on:
      - wordpress
volumes:
  dbdata:
  wp_data:
  wp_db_data:
  dbdata-test:
