version: "3.8"

services:
  augustin-db:
    container_name: augustin-db
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  augustin:
    container_name: augustin
    build:
      context: .
      dockerfile: Dockerfile.production
    command: "cd migrations && tern migrate && cd .. && ./app -prod"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@augustin-db:5432/${DB_NAME}?sslmode=disable
    volumes:
      - ./img:/img
      - ./doc:/doc
    depends_on:
      augustin-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    links:
      - augustin-db
      - keycloak
    ports:
      - "3000:3000"
  keycloak:
    build: ./docker/keycloak
    container_name: augustin-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_SERVER_URL}
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: DEBUG
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/realms/master"]
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/export:/tmp/export
    command: start-dev --import-realm
    ports:
      - "8080:8080"
volumes:
  dbdata:
