basePath: /api
consumes:
- application/json
definitions:
  database.Item:
    properties:
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  database.Payment:
    properties:
      amount:
        type: number
      authorizedBy:
        type: string
      batch:
        type: integer
      id:
        type: integer
      item:
        type: integer
      receiver:
        type: integer
      sender:
        type: integer
      timestamp:
        format: date-time
        type: string
    type: object
  database.Settings:
    properties:
      color:
        type: string
      id:
        type: integer
      logo:
        type: string
      mainItem:
        type: integer
      refundFees:
        type: boolean
    type: object
  database.Vendor:
    properties:
      balance:
        description: This is joined in from the account
        type: number
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      keycloakID:
        type: string
      lastName:
        type: string
      lastPayout:
        format: date-time
        type: string
      licenseID:
        type: string
      urlID:
        description: This is used for the QR code
        type: string
    type: object
  handlers.TransactionOrder:
    properties:
      amount:
        type: integer
    type: object
  handlers.TransactionOrderResponse:
    properties:
      smartCheckoutURL:
        type: string
    type: object
  handlers.TransactionVerification:
    properties:
      transactionID:
        type: string
    type: object
  handlers.TransactionVerificationResponse:
    properties:
      verification:
        type: boolean
    type: object
  handlers.VivaWalletVerificationKeyResponse:
    properties:
      key:
        type: string
    type: object
  paymentprovider.PaymentSuccessfulResponse:
    properties:
      CorrelationId:
        type: string
      Created:
        type: string
      Delay:
        type: string
      EventTypeId:
        type: integer
      MessageId:
        type: string
      MessageTypeId:
        type: integer
      RecipientId:
        type: string
      eventData:
        properties:
          amount:
            type: integer
          assignedMerchantUsers:
            items:
              type: string
            type: array
          assignedResellerUsers:
            items:
              type: string
            type: array
          bankId:
            type: string
          billId:
            type: string
          cardCountryCode:
            type: string
          cardExpirationDate:
            type: string
          cardIssuingBank:
            type: string
          cardNumber:
            type: string
          cardToken:
            type: string
          cardTypeId:
            type: integer
          cardUniqueReference:
            type: string
          channelId:
            type: string
          clearanceDate:
            type: string
          companyName:
            type: string
          companyTitle:
            type: string
          currencyCode:
            type: string
          currentInstallment:
            type: integer
          customerTrns:
            type: string
          digitalWalletId:
            type: integer
          electronicCommerceIndicator:
            type: string
          email:
            type: string
          fullName:
            type: string
          insDate:
            type: string
          isManualRefund:
            type: boolean
          latitude:
            type: string
          longitude:
            type: string
          loyaltyTriggered:
            type: boolean
          merchantId:
            type: string
          merchantTrns:
            type: string
          moto:
            type: boolean
          orderCode:
            type: integer
          orderCulture:
            type: string
          panEntryMode:
            type: string
          parentId:
            type: string
          phone:
            type: string
          productId:
            type: string
          redeemedAmount:
            type: integer
          referenceNumber:
            type: integer
          resellerCompanyName:
            type: string
          resellerId:
            type: string
          resellerSourceAddress:
            type: string
          resellerSourceCode:
            type: string
          resellerSourceName:
            type: string
          responseCode:
            type: string
          responseEventId:
            type: string
          retrievalReferenceNumber:
            type: string
          sourceCode:
            type: string
          sourceName:
            type: string
          statusId:
            type: string
          switching:
            type: boolean
          systemic:
            type: boolean
          tags:
            items:
              type: string
            type: array
          targetPersonId:
            type: string
          targetWalletId:
            type: string
          terminalId:
            type: integer
          tipAmount:
            type: integer
          totalFee:
            type: integer
          totalInstallments:
            type: integer
          transactionId:
            type: string
          transactionTypeId:
            type: integer
        type: object
      url:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This swagger describes every endpoint of this project.
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  termsOfService: http://swagger.io/terms/
  title: Augustin Swagger
  version: 0.0.1
paths:
  /hello/:
    get:
      consumes:
      - application/json
      description: Return HelloWorld as sample API call
      produces:
      - application/json
      responses: {}
      summary: Return HelloWorld
      tags:
      - core
  /items/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Item'
            type: array
      summary: List Items
      tags:
      - Items
    post:
      consumes:
      - application/json
      parameters:
      - description: Item Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: Create Item
      tags:
      - Items
  /items/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Item
      tags:
      - Items
  /items/{id}/:
    put:
      consumes:
      - application/json
      description: Requires multipart form (for image)
      parameters:
      - description: Item Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Item
      tags:
      - Items
  /payments:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Payment'
            type: array
      summary: Get list of all payments
      tags:
      - core
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a set of payments
      tags:
      - core
  /settings/:
    get:
      consumes:
      - application/json
      description: Return configuration data of the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Settings'
            type: array
      summary: Return settings
      tags:
      - core
  /vendors/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Vendor'
            type: array
      summary: List Vendors
      tags:
      - vendors
    post:
      consumes:
      - application/json
      parameters:
      - description: Vendor Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Vendor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Vendor
      tags:
      - vendors
  /vendors/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Vendor ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Vendor
      tags:
      - vendors
    put:
      consumes:
      - application/json
      description: 'Warning: Unfilled fields will be set to default values'
      parameters:
      - description: Vendor ID
        in: path
        name: id
        required: true
        type: integer
      - description: Vendor Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Vendor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Vendor
      tags:
      - vendors
  /vivawallet/transaction_order/:
    post:
      consumes:
      - application/json
      description: Post your amount like {"Amount":100}, which equals 100 cents
      parameters:
      - description: Amount in cents
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/handlers.TransactionOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.TransactionOrderResponse'
            type: array
      summary: Create a transaction order
      tags:
      - core
  /vivawallet/transaction_verification/:
    post:
      consumes:
      - application/json
      description: Accepts {"TransactionID":"1234567890"} and returns {"Verification":true},
        if successful
      parameters:
      - description: Transaction ID
        in: body
        name: transactionID
        required: true
        schema:
          $ref: '#/definitions/handlers.TransactionVerification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.TransactionVerificationResponse'
            type: array
      summary: Verify a transaction
      tags:
      - core
  /webhooks/vivawallet/:
    get:
      consumes:
      - application/json
      description: Return VivaWallet verification key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.VivaWalletVerificationKeyResponse'
            type: array
      summary: Return VivaWallet verification key
      tags:
      - core
    post:
      consumes:
      - application/json
      description: Webhook for VivaWallet
      parameters:
      - description: Payment Successful Response
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/paymentprovider.PaymentSuccessfulResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Webhook for VivaWallet
      tags:
      - core
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
