basePath: /api
consumes:
- application/json
definitions:
  database.Item:
    properties:
      archived:
        type: boolean
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      licenseItem:
        allOf:
        - $ref: '#/definitions/null.Int'
        description: License has to be bought before item
      name:
        type: string
      price:
        description: Price in cents
        type: integer
    type: object
  database.Payment:
    properties:
      amount:
        type: integer
      authorizedBy:
        type: string
      id:
        type: integer
      order:
        type: integer
      orderEntry:
        type: integer
      receiver:
        type: integer
      sender:
        type: integer
      timestamp:
        type: string
    type: object
  database.Settings:
    properties:
      color:
        type: string
      id:
        type: integer
      logo:
        type: string
      mainItem:
        type: integer
      refundFees:
        type: boolean
    type: object
  database.Vendor:
    properties:
      balance:
        description: This is joined in from the account
        type: integer
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      keycloakID:
        type: string
      lastName:
        type: string
      lastPayout:
        format: date-time
        type: string
      licenseID:
        type: string
      urlid:
        description: This is used for the QR code
        type: string
    type: object
  handlers.createOrderRequest:
    properties:
      entries:
        items:
          $ref: '#/definitions/handlers.createOrderRequestEntry'
        type: array
      user:
        type: string
      vendor:
        type: integer
    type: object
  handlers.createOrderRequestEntry:
    properties:
      item:
        type: integer
      quantity:
        type: integer
    type: object
  handlers.createOrderResponse:
    properties:
      smartCheckoutURL:
        type: string
    type: object
  handlers.createPaymentPayoutRequest:
    properties:
      amount:
        type: integer
      vendorLicenseID:
        type: string
    type: object
  handlers.createPaymentsRequest:
    properties:
      payments:
        items:
          $ref: '#/definitions/database.Payment'
        type: array
    type: object
  null.Int:
    properties:
      int64:
        type: integer
      valid:
        description: Valid is true if Int64 is not NULL
        type: boolean
    type: object
  paymentprovider.EventData:
    properties:
      AcquirerApproved:
        type: boolean
      Amount:
        type: number
      AssignedMerchantUsers:
        items: {}
        type: array
      AssignedResellerUsers:
        items: {}
        type: array
      AuthorizationId:
        type: string
      BankId:
        type: string
      BillId: {}
      BinId:
        type: integer
      CardCountryCode: {}
      CardExpirationDate:
        type: string
      CardIssuingBank: {}
      CardNumber:
        type: string
      CardToken:
        type: string
      CardTypeId:
        type: integer
      CardUniqueReference:
        type: string
      ChannelId:
        type: string
      ClearanceDate: {}
      CompanyName: {}
      CompanyTitle: {}
      ConnectedAccountId: {}
      CurrencyCode:
        type: string
      CurrentInstallment:
        type: integer
      CustomerTrns:
        type: string
      DigitalWalletId: {}
      DualMessage:
        type: boolean
      ElectronicCommerceIndicator:
        type: string
      Email:
        type: string
      FullName:
        type: string
      InsDate:
        type: string
      IsManualRefund:
        type: boolean
      Latitude: {}
      Longitude: {}
      LoyaltyTriggered:
        type: boolean
      MerchantCategoryCode:
        type: integer
      MerchantId:
        type: string
      MerchantTrns:
        type: string
      Moto:
        type: boolean
      OrderCode:
        type: integer
      OrderCulture:
        type: string
      OrderServiceId:
        type: integer
      PanEntryMode:
        type: string
      ParentId: {}
      Phone:
        type: string
      ProductId: {}
      RedeemedAmount:
        type: number
      ReferenceNumber:
        type: integer
      ResellerCompanyName: {}
      ResellerId: {}
      ResellerSourceAddress: {}
      ResellerSourceCode: {}
      ResellerSourceName: {}
      ResponseCode:
        type: string
      ResponseEventId: {}
      RetrievalReferenceNumber:
        type: string
      ServiceId: {}
      SourceCode:
        type: string
      SourceName:
        type: string
      StatusId:
        type: string
      Switching:
        type: boolean
      Systemic:
        type: boolean
      Tags:
        items:
          type: string
        type: array
      TargetPersonId: {}
      TargetWalletId: {}
      TerminalId:
        type: integer
      TipAmount:
        type: number
      TotalFee:
        type: number
      TotalInstallments:
        type: integer
      TransactionId:
        type: string
      TransactionTypeId:
        type: integer
      Ucaf:
        type: string
    type: object
  paymentprovider.PriceEventData:
    properties:
      CurrencyCode:
        type: string
      Interchange:
        type: number
      IsvFee:
        type: number
      MerchantId:
        type: string
      OrderCode:
        type: integer
      TotalCommission:
        type: number
      TransactionId:
        type: string
    type: object
  paymentprovider.TransactionDetailRequest:
    properties:
      CorrelationId:
        type: string
      Created:
        type: string
      Delay: {}
      EventData:
        $ref: '#/definitions/paymentprovider.EventData'
      EventTypeId:
        type: integer
      MessageId:
        type: string
      MessageTypeId:
        type: integer
      RecipientId:
        type: string
      Url:
        type: string
    type: object
  paymentprovider.TransactionPriceRequest:
    properties:
      CorrelationId:
        type: string
      Created:
        type: string
      Delay:
        type: integer
      EventData:
        $ref: '#/definitions/paymentprovider.PriceEventData'
      EventTypeId:
        type: integer
      MessageId:
        type: string
      MessageTypeId:
        type: integer
      RecipientId:
        type: string
      Url:
        type: string
    type: object
  paymentprovider.VivaWalletVerificationKeyResponse:
    properties:
      key:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This swagger describes every endpoint of this project.
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  termsOfService: http://swagger.io/terms/
  title: Augustin Swagger
  version: 0.0.1
paths:
  /hello/:
    get:
      consumes:
      - application/json
      description: Return HelloWorld as sample API call
      produces:
      - application/json
      responses: {}
      summary: Return HelloWorld
      tags:
      - core
  /items/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Item'
            type: array
      summary: List Items
      tags:
      - Items
    post:
      consumes:
      - application/json
      parameters:
      - description: Item Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Create Item
      tags:
      - Items
  /items/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Item
      tags:
      - Items
  /items/{id}/:
    put:
      consumes:
      - application/json
      description: Requires multipart form (for image)
      parameters:
      - description: Item Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Item
      tags:
      - Items
  /orders/:
    post:
      consumes:
      - application/json
      description: Submits payment order to provider & saves it to database. Entries
        need to have an item id and a quantity (for entries without a price like tips,
        the quantity is the amount of cents). If no user is given, the order is anonymous.
      parameters:
      - description: Payment Order
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.createOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.createOrderResponse'
      summary: Create Payment Order
      tags:
      - Orders
  /payments/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Payment'
            type: array
      summary: Get list of all payments
      tags:
      - Payments
    post:
      consumes:
      - application/json
      parameters:
      - description: ' Create Payment'
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/database.Payment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a payment
      tags:
      - Payments
  /payments/batch/:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' Create Payment'
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/handlers.createPaymentsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Create a set of payments
      tags:
      - Payments
  /payments/payout/:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' Create Payment'
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/handlers.createPaymentPayoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Create a payment from a vendor account to cash
      tags:
      - Payments
  /settings/:
    get:
      consumes:
      - application/json
      description: Return configuration data of the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Settings'
            type: array
      summary: Return settings
      tags:
      - core
    put:
      consumes:
      - application/json
      description: Update configuration data of the system
      parameters:
      - description: Settings Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Settings'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update settings
      tags:
      - core
  /vendors/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Vendor'
            type: array
      summary: List Vendors
      tags:
      - vendors
    post:
      consumes:
      - application/json
      parameters:
      - description: Vendor Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Vendor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Vendor
      tags:
      - vendors
  /vendors/{id}/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Vendor ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Vendor
      tags:
      - vendors
    put:
      consumes:
      - application/json
      description: 'Warning: Unfilled fields will be set to default values'
      parameters:
      - description: Vendor ID
        in: path
        name: id
        required: true
        type: integer
      - description: Vendor Representation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/database.Vendor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Vendor
      tags:
      - vendors
  /webhooks/vivawallet/failure:
    get:
      consumes:
      - application/json
      description: Return VivaWallet verification key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/paymentprovider.VivaWalletVerificationKeyResponse'
            type: array
      summary: Return VivaWallet verification key
      tags:
      - core
    post:
      consumes:
      - application/json
      description: Webhook for VivaWallet failed transaction
      parameters:
      - description: Payment Failure Response
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/paymentprovider.TransactionDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Webhook for VivaWallet failed transaction
      tags:
      - core
  /webhooks/vivawallet/price:
    get:
      consumes:
      - application/json
      description: Return VivaWallet verification key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/paymentprovider.VivaWalletVerificationKeyResponse'
            type: array
      summary: Return VivaWallet verification key
      tags:
      - core
    post:
      consumes:
      - application/json
      description: Webhook for VivaWallet transaction prices
      parameters:
      - description: Payment Price Response
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/paymentprovider.TransactionPriceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Webhook for VivaWallet transaction prices
      tags:
      - core
  /webhooks/vivawallet/success:
    get:
      consumes:
      - application/json
      description: Return VivaWallet verification key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/paymentprovider.VivaWalletVerificationKeyResponse'
            type: array
      summary: Return VivaWallet verification key
      tags:
      - core
    post:
      consumes:
      - application/json
      description: Webhook for VivaWallet successful transaction
      parameters:
      - description: Payment Successful Response
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/paymentprovider.TransactionDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Webhook for VivaWallet successful transaction
      tags:
      - core
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
