// Code generated by ent, DO NOT EDIT.

package blockedip

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the blockedip type in the database.
	Label = "blocked_ip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldStrikes holds the string denoting the strikes field in the database.
	FieldStrikes = "strikes"
	// FieldBlockExpiresAt holds the string denoting the block_expires_at field in the database.
	FieldBlockExpiresAt = "block_expires_at"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// Table holds the table name of the blockedip in the database.
	Table = "blocked_ips"
)

// Columns holds all SQL columns for blockedip fields.
var Columns = []string{
	FieldID,
	FieldIP,
	FieldStrikes,
	FieldBlockExpiresAt,
	FieldReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPValidator is a validator for the "ip" field. It is called by the builders before save.
	IPValidator func(string) error
	// DefaultStrikes holds the default value on creation for the "strikes" field.
	DefaultStrikes int
)

// OrderOption defines the ordering options for the BlockedIP queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByStrikes orders the results by the strikes field.
func ByStrikes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrikes, opts...).ToFunc()
}

// ByBlockExpiresAt orders the results by the block_expires_at field.
func ByBlockExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockExpiresAt, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}
