// Code generated by ent, DO NOT EDIT.

package payment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldAuthorizedBy holds the string denoting the authorized_by field in the database.
	FieldAuthorizedBy = "authorized_by"
	// FieldIsSale holds the string denoting the is_sale field in the database.
	FieldIsSale = "is_sale"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender"
	// FieldReceiverID holds the string denoting the receiver_id field in the database.
	FieldReceiverID = "receiver"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "paymentorder"
	// FieldOrderEntryID holds the string denoting the order_entry_id field in the database.
	FieldOrderEntryID = "order_entry"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item"
	// FieldPayoutID holds the string denoting the payout_id field in the database.
	FieldPayoutID = "payout"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// Table holds the table name of the payment in the database.
	Table = "payment"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "payment"
	// OrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderInverseTable = "paymentorder"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "paymentorder"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "payment"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "payout"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "payment"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "payout"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldAmount,
	FieldAuthorizedBy,
	FieldIsSale,
	FieldQuantity,
	FieldPrice,
	FieldSenderID,
	FieldReceiverID,
	FieldOrderID,
	FieldOrderEntryID,
	FieldItemID,
	FieldPayoutID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByAuthorizedBy orders the results by the authorized_by field.
func ByAuthorizedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizedBy, opts...).ToFunc()
}

// ByIsSale orders the results by the is_sale field.
func ByIsSale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSale, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// ByReceiverID orders the results by the receiver_id field.
func ByReceiverID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiverID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByOrderEntryID orders the results by the order_entry_id field.
func ByOrderEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderEntryID, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByPayoutID orders the results by the payout_id field.
func ByPayoutID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayoutID, opts...).ToFunc()
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
	)
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
