// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/abonement"
	"github.com/augustin-wien/augustina-backend/ent/customer"
	"github.com/augustin-wien/augustina-backend/ent/item"
)

// AbonementCreate is the builder for creating a Abonement entity.
type AbonementCreate struct {
	config
	mutation *AbonementMutation
	hooks    []Hook
}

// SetCustomerID sets the "customer_id" field.
func (ac *AbonementCreate) SetCustomerID(i int) *AbonementCreate {
	ac.mutation.SetCustomerID(i)
	return ac
}

// SetItemID sets the "item_id" field.
func (ac *AbonementCreate) SetItemID(i int) *AbonementCreate {
	ac.mutation.SetItemID(i)
	return ac
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (ac *AbonementCreate) SetNillableItemID(i *int) *AbonementCreate {
	if i != nil {
		ac.SetItemID(*i)
	}
	return ac
}

// SetFromDate sets the "from_date" field.
func (ac *AbonementCreate) SetFromDate(t time.Time) *AbonementCreate {
	ac.mutation.SetFromDate(t)
	return ac
}

// SetToDate sets the "to_date" field.
func (ac *AbonementCreate) SetToDate(t time.Time) *AbonementCreate {
	ac.mutation.SetToDate(t)
	return ac
}

// SetStatus sets the "status" field.
func (ac *AbonementCreate) SetStatus(s string) *AbonementCreate {
	ac.mutation.SetStatus(s)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AbonementCreate) SetNillableStatus(s *string) *AbonementCreate {
	if s != nil {
		ac.SetStatus(*s)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AbonementCreate) SetCreatedAt(t time.Time) *AbonementCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AbonementCreate) SetNillableCreatedAt(t *time.Time) *AbonementCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AbonementCreate) SetUpdatedAt(t time.Time) *AbonementCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AbonementCreate) SetNillableUpdatedAt(t *time.Time) *AbonementCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AbonementCreate) SetID(i int) *AbonementCreate {
	ac.mutation.SetID(i)
	return ac
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (ac *AbonementCreate) SetCustomer(c *Customer) *AbonementCreate {
	return ac.SetCustomerID(c.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (ac *AbonementCreate) SetItem(i *Item) *AbonementCreate {
	return ac.SetItemID(i.ID)
}

// Mutation returns the AbonementMutation object of the builder.
func (ac *AbonementCreate) Mutation() *AbonementMutation {
	return ac.mutation
}

// Save creates the Abonement in the database.
func (ac *AbonementCreate) Save(ctx context.Context) (*Abonement, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AbonementCreate) SaveX(ctx context.Context) *Abonement {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AbonementCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AbonementCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AbonementCreate) defaults() {
	if _, ok := ac.mutation.Status(); !ok {
		v := abonement.DefaultStatus
		ac.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AbonementCreate) check() error {
	if _, ok := ac.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Abonement.customer_id"`)}
	}
	if _, ok := ac.mutation.FromDate(); !ok {
		return &ValidationError{Name: "from_date", err: errors.New(`ent: missing required field "Abonement.from_date"`)}
	}
	if _, ok := ac.mutation.ToDate(); !ok {
		return &ValidationError{Name: "to_date", err: errors.New(`ent: missing required field "Abonement.to_date"`)}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Abonement.status"`)}
	}
	if v, ok := ac.mutation.ID(); ok {
		if err := abonement.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Abonement.id": %w`, err)}
		}
	}
	if len(ac.mutation.CustomerIDs()) == 0 {
		return &ValidationError{Name: "customer", err: errors.New(`ent: missing required edge "Abonement.customer"`)}
	}
	return nil
}

func (ac *AbonementCreate) sqlSave(ctx context.Context) (*Abonement, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AbonementCreate) createSpec() (*Abonement, *sqlgraph.CreateSpec) {
	var (
		_node = &Abonement{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(abonement.Table, sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.FromDate(); ok {
		_spec.SetField(abonement.FieldFromDate, field.TypeTime, value)
		_node.FromDate = value
	}
	if value, ok := ac.mutation.ToDate(); ok {
		_spec.SetField(abonement.FieldToDate, field.TypeTime, value)
		_node.ToDate = value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(abonement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(abonement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(abonement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := ac.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   abonement.CustomerTable,
			Columns: []string{abonement.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   abonement.ItemTable,
			Columns: []string{abonement.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AbonementCreateBulk is the builder for creating many Abonement entities in bulk.
type AbonementCreateBulk struct {
	config
	err      error
	builders []*AbonementCreate
}

// Save creates the Abonement entities in the database.
func (acb *AbonementCreateBulk) Save(ctx context.Context) ([]*Abonement, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Abonement, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AbonementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AbonementCreateBulk) SaveX(ctx context.Context) []*Abonement {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AbonementCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AbonementCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
