// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/blockedip"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// BlockedIPQuery is the builder for querying BlockedIP entities.
type BlockedIPQuery struct {
	config
	ctx        *QueryContext
	order      []blockedip.OrderOption
	inters     []Interceptor
	predicates []predicate.BlockedIP
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlockedIPQuery builder.
func (biq *BlockedIPQuery) Where(ps ...predicate.BlockedIP) *BlockedIPQuery {
	biq.predicates = append(biq.predicates, ps...)
	return biq
}

// Limit the number of records to be returned by this query.
func (biq *BlockedIPQuery) Limit(limit int) *BlockedIPQuery {
	biq.ctx.Limit = &limit
	return biq
}

// Offset to start from.
func (biq *BlockedIPQuery) Offset(offset int) *BlockedIPQuery {
	biq.ctx.Offset = &offset
	return biq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (biq *BlockedIPQuery) Unique(unique bool) *BlockedIPQuery {
	biq.ctx.Unique = &unique
	return biq
}

// Order specifies how the records should be ordered.
func (biq *BlockedIPQuery) Order(o ...blockedip.OrderOption) *BlockedIPQuery {
	biq.order = append(biq.order, o...)
	return biq
}

// First returns the first BlockedIP entity from the query.
// Returns a *NotFoundError when no BlockedIP was found.
func (biq *BlockedIPQuery) First(ctx context.Context) (*BlockedIP, error) {
	nodes, err := biq.Limit(1).All(setContextOp(ctx, biq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blockedip.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (biq *BlockedIPQuery) FirstX(ctx context.Context) *BlockedIP {
	node, err := biq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlockedIP ID from the query.
// Returns a *NotFoundError when no BlockedIP ID was found.
func (biq *BlockedIPQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = biq.Limit(1).IDs(setContextOp(ctx, biq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blockedip.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (biq *BlockedIPQuery) FirstIDX(ctx context.Context) int {
	id, err := biq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlockedIP entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlockedIP entity is found.
// Returns a *NotFoundError when no BlockedIP entities are found.
func (biq *BlockedIPQuery) Only(ctx context.Context) (*BlockedIP, error) {
	nodes, err := biq.Limit(2).All(setContextOp(ctx, biq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blockedip.Label}
	default:
		return nil, &NotSingularError{blockedip.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (biq *BlockedIPQuery) OnlyX(ctx context.Context) *BlockedIP {
	node, err := biq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlockedIP ID in the query.
// Returns a *NotSingularError when more than one BlockedIP ID is found.
// Returns a *NotFoundError when no entities are found.
func (biq *BlockedIPQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = biq.Limit(2).IDs(setContextOp(ctx, biq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blockedip.Label}
	default:
		err = &NotSingularError{blockedip.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (biq *BlockedIPQuery) OnlyIDX(ctx context.Context) int {
	id, err := biq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlockedIPs.
func (biq *BlockedIPQuery) All(ctx context.Context) ([]*BlockedIP, error) {
	ctx = setContextOp(ctx, biq.ctx, ent.OpQueryAll)
	if err := biq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlockedIP, *BlockedIPQuery]()
	return withInterceptors[[]*BlockedIP](ctx, biq, qr, biq.inters)
}

// AllX is like All, but panics if an error occurs.
func (biq *BlockedIPQuery) AllX(ctx context.Context) []*BlockedIP {
	nodes, err := biq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlockedIP IDs.
func (biq *BlockedIPQuery) IDs(ctx context.Context) (ids []int, err error) {
	if biq.ctx.Unique == nil && biq.path != nil {
		biq.Unique(true)
	}
	ctx = setContextOp(ctx, biq.ctx, ent.OpQueryIDs)
	if err = biq.Select(blockedip.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (biq *BlockedIPQuery) IDsX(ctx context.Context) []int {
	ids, err := biq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (biq *BlockedIPQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, biq.ctx, ent.OpQueryCount)
	if err := biq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, biq, querierCount[*BlockedIPQuery](), biq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (biq *BlockedIPQuery) CountX(ctx context.Context) int {
	count, err := biq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (biq *BlockedIPQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, biq.ctx, ent.OpQueryExist)
	switch _, err := biq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (biq *BlockedIPQuery) ExistX(ctx context.Context) bool {
	exist, err := biq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlockedIPQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (biq *BlockedIPQuery) Clone() *BlockedIPQuery {
	if biq == nil {
		return nil
	}
	return &BlockedIPQuery{
		config:     biq.config,
		ctx:        biq.ctx.Clone(),
		order:      append([]blockedip.OrderOption{}, biq.order...),
		inters:     append([]Interceptor{}, biq.inters...),
		predicates: append([]predicate.BlockedIP{}, biq.predicates...),
		// clone intermediate query.
		sql:  biq.sql.Clone(),
		path: biq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IP string `json:"ip,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlockedIP.Query().
//		GroupBy(blockedip.FieldIP).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (biq *BlockedIPQuery) GroupBy(field string, fields ...string) *BlockedIPGroupBy {
	biq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlockedIPGroupBy{build: biq}
	grbuild.flds = &biq.ctx.Fields
	grbuild.label = blockedip.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IP string `json:"ip,omitempty"`
//	}
//
//	client.BlockedIP.Query().
//		Select(blockedip.FieldIP).
//		Scan(ctx, &v)
func (biq *BlockedIPQuery) Select(fields ...string) *BlockedIPSelect {
	biq.ctx.Fields = append(biq.ctx.Fields, fields...)
	sbuild := &BlockedIPSelect{BlockedIPQuery: biq}
	sbuild.label = blockedip.Label
	sbuild.flds, sbuild.scan = &biq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlockedIPSelect configured with the given aggregations.
func (biq *BlockedIPQuery) Aggregate(fns ...AggregateFunc) *BlockedIPSelect {
	return biq.Select().Aggregate(fns...)
}

func (biq *BlockedIPQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range biq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, biq); err != nil {
				return err
			}
		}
	}
	for _, f := range biq.ctx.Fields {
		if !blockedip.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if biq.path != nil {
		prev, err := biq.path(ctx)
		if err != nil {
			return err
		}
		biq.sql = prev
	}
	return nil
}

func (biq *BlockedIPQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlockedIP, error) {
	var (
		nodes = []*BlockedIP{}
		_spec = biq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlockedIP).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlockedIP{config: biq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, biq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (biq *BlockedIPQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := biq.querySpec()
	_spec.Node.Columns = biq.ctx.Fields
	if len(biq.ctx.Fields) > 0 {
		_spec.Unique = biq.ctx.Unique != nil && *biq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, biq.driver, _spec)
}

func (biq *BlockedIPQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blockedip.Table, blockedip.Columns, sqlgraph.NewFieldSpec(blockedip.FieldID, field.TypeInt))
	_spec.From = biq.sql
	if unique := biq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if biq.path != nil {
		_spec.Unique = true
	}
	if fields := biq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockedip.FieldID)
		for i := range fields {
			if fields[i] != blockedip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := biq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := biq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := biq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := biq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (biq *BlockedIPQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(biq.driver.Dialect())
	t1 := builder.Table(blockedip.Table)
	columns := biq.ctx.Fields
	if len(columns) == 0 {
		columns = blockedip.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if biq.sql != nil {
		selector = biq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if biq.ctx.Unique != nil && *biq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range biq.predicates {
		p(selector)
	}
	for _, p := range biq.order {
		p(selector)
	}
	if offset := biq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := biq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlockedIPGroupBy is the group-by builder for BlockedIP entities.
type BlockedIPGroupBy struct {
	selector
	build *BlockedIPQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bigb *BlockedIPGroupBy) Aggregate(fns ...AggregateFunc) *BlockedIPGroupBy {
	bigb.fns = append(bigb.fns, fns...)
	return bigb
}

// Scan applies the selector query and scans the result into the given value.
func (bigb *BlockedIPGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bigb.build.ctx, ent.OpQueryGroupBy)
	if err := bigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockedIPQuery, *BlockedIPGroupBy](ctx, bigb.build, bigb, bigb.build.inters, v)
}

func (bigb *BlockedIPGroupBy) sqlScan(ctx context.Context, root *BlockedIPQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bigb.fns))
	for _, fn := range bigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bigb.flds)+len(bigb.fns))
		for _, f := range *bigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlockedIPSelect is the builder for selecting fields of BlockedIP entities.
type BlockedIPSelect struct {
	*BlockedIPQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bis *BlockedIPSelect) Aggregate(fns ...AggregateFunc) *BlockedIPSelect {
	bis.fns = append(bis.fns, fns...)
	return bis
}

// Scan applies the selector query and scans the result into the given value.
func (bis *BlockedIPSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bis.ctx, ent.OpQuerySelect)
	if err := bis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockedIPQuery, *BlockedIPSelect](ctx, bis.BlockedIPQuery, bis, bis.inters, v)
}

func (bis *BlockedIPSelect) sqlScan(ctx context.Context, root *BlockedIPQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bis.fns))
	for _, fn := range bis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
