// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/abonement"
	"github.com/augustin-wien/augustina-backend/ent/customer"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// CustomerUpdate is the builder for updating Customer entities.
type CustomerUpdate struct {
	config
	hooks    []Hook
	mutation *CustomerMutation
}

// Where appends a list predicates to the CustomerUpdate builder.
func (cu *CustomerUpdate) Where(ps ...predicate.Customer) *CustomerUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetKeycloakid sets the "keycloakid" field.
func (cu *CustomerUpdate) SetKeycloakid(s string) *CustomerUpdate {
	cu.mutation.SetKeycloakid(s)
	return cu
}

// SetNillableKeycloakid sets the "keycloakid" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableKeycloakid(s *string) *CustomerUpdate {
	if s != nil {
		cu.SetKeycloakid(*s)
	}
	return cu
}

// SetEmail sets the "email" field.
func (cu *CustomerUpdate) SetEmail(s string) *CustomerUpdate {
	cu.mutation.SetEmail(s)
	return cu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableEmail(s *string) *CustomerUpdate {
	if s != nil {
		cu.SetEmail(*s)
	}
	return cu
}

// SetFirstname sets the "firstname" field.
func (cu *CustomerUpdate) SetFirstname(s string) *CustomerUpdate {
	cu.mutation.SetFirstname(s)
	return cu
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableFirstname(s *string) *CustomerUpdate {
	if s != nil {
		cu.SetFirstname(*s)
	}
	return cu
}

// SetLastname sets the "lastname" field.
func (cu *CustomerUpdate) SetLastname(s string) *CustomerUpdate {
	cu.mutation.SetLastname(s)
	return cu
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableLastname(s *string) *CustomerUpdate {
	if s != nil {
		cu.SetLastname(*s)
	}
	return cu
}

// SetLicensegroups sets the "licensegroups" field.
func (cu *CustomerUpdate) SetLicensegroups(s string) *CustomerUpdate {
	cu.mutation.SetLicensegroups(s)
	return cu
}

// SetNillableLicensegroups sets the "licensegroups" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableLicensegroups(s *string) *CustomerUpdate {
	if s != nil {
		cu.SetLicensegroups(*s)
	}
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CustomerUpdate) SetCreatedAt(t time.Time) *CustomerUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableCreatedAt(t *time.Time) *CustomerUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (cu *CustomerUpdate) ClearCreatedAt() *CustomerUpdate {
	cu.mutation.ClearCreatedAt()
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CustomerUpdate) SetUpdatedAt(t time.Time) *CustomerUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *CustomerUpdate) SetNillableUpdatedAt(t *time.Time) *CustomerUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (cu *CustomerUpdate) ClearUpdatedAt() *CustomerUpdate {
	cu.mutation.ClearUpdatedAt()
	return cu
}

// AddAbonementIDs adds the "abonements" edge to the Abonement entity by IDs.
func (cu *CustomerUpdate) AddAbonementIDs(ids ...int) *CustomerUpdate {
	cu.mutation.AddAbonementIDs(ids...)
	return cu
}

// AddAbonements adds the "abonements" edges to the Abonement entity.
func (cu *CustomerUpdate) AddAbonements(a ...*Abonement) *CustomerUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.AddAbonementIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (cu *CustomerUpdate) Mutation() *CustomerMutation {
	return cu.mutation
}

// ClearAbonements clears all "abonements" edges to the Abonement entity.
func (cu *CustomerUpdate) ClearAbonements() *CustomerUpdate {
	cu.mutation.ClearAbonements()
	return cu
}

// RemoveAbonementIDs removes the "abonements" edge to Abonement entities by IDs.
func (cu *CustomerUpdate) RemoveAbonementIDs(ids ...int) *CustomerUpdate {
	cu.mutation.RemoveAbonementIDs(ids...)
	return cu
}

// RemoveAbonements removes "abonements" edges to Abonement entities.
func (cu *CustomerUpdate) RemoveAbonements(a ...*Abonement) *CustomerUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.RemoveAbonementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CustomerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CustomerUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CustomerUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CustomerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Keycloakid(); ok {
		_spec.SetField(customer.FieldKeycloakid, field.TypeString, value)
	}
	if value, ok := cu.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
	}
	if value, ok := cu.mutation.Firstname(); ok {
		_spec.SetField(customer.FieldFirstname, field.TypeString, value)
	}
	if value, ok := cu.mutation.Lastname(); ok {
		_spec.SetField(customer.FieldLastname, field.TypeString, value)
	}
	if value, ok := cu.mutation.Licensegroups(); ok {
		_spec.SetField(customer.FieldLicensegroups, field.TypeString, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
	}
	if cu.mutation.CreatedAtCleared() {
		_spec.ClearField(customer.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
	}
	if cu.mutation.UpdatedAtCleared() {
		_spec.ClearField(customer.FieldUpdatedAt, field.TypeTime)
	}
	if cu.mutation.AbonementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedAbonementsIDs(); len(nodes) > 0 && !cu.mutation.AbonementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AbonementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CustomerUpdateOne is the builder for updating a single Customer entity.
type CustomerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomerMutation
}

// SetKeycloakid sets the "keycloakid" field.
func (cuo *CustomerUpdateOne) SetKeycloakid(s string) *CustomerUpdateOne {
	cuo.mutation.SetKeycloakid(s)
	return cuo
}

// SetNillableKeycloakid sets the "keycloakid" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableKeycloakid(s *string) *CustomerUpdateOne {
	if s != nil {
		cuo.SetKeycloakid(*s)
	}
	return cuo
}

// SetEmail sets the "email" field.
func (cuo *CustomerUpdateOne) SetEmail(s string) *CustomerUpdateOne {
	cuo.mutation.SetEmail(s)
	return cuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableEmail(s *string) *CustomerUpdateOne {
	if s != nil {
		cuo.SetEmail(*s)
	}
	return cuo
}

// SetFirstname sets the "firstname" field.
func (cuo *CustomerUpdateOne) SetFirstname(s string) *CustomerUpdateOne {
	cuo.mutation.SetFirstname(s)
	return cuo
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableFirstname(s *string) *CustomerUpdateOne {
	if s != nil {
		cuo.SetFirstname(*s)
	}
	return cuo
}

// SetLastname sets the "lastname" field.
func (cuo *CustomerUpdateOne) SetLastname(s string) *CustomerUpdateOne {
	cuo.mutation.SetLastname(s)
	return cuo
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableLastname(s *string) *CustomerUpdateOne {
	if s != nil {
		cuo.SetLastname(*s)
	}
	return cuo
}

// SetLicensegroups sets the "licensegroups" field.
func (cuo *CustomerUpdateOne) SetLicensegroups(s string) *CustomerUpdateOne {
	cuo.mutation.SetLicensegroups(s)
	return cuo
}

// SetNillableLicensegroups sets the "licensegroups" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableLicensegroups(s *string) *CustomerUpdateOne {
	if s != nil {
		cuo.SetLicensegroups(*s)
	}
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CustomerUpdateOne) SetCreatedAt(t time.Time) *CustomerUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableCreatedAt(t *time.Time) *CustomerUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (cuo *CustomerUpdateOne) ClearCreatedAt() *CustomerUpdateOne {
	cuo.mutation.ClearCreatedAt()
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CustomerUpdateOne) SetUpdatedAt(t time.Time) *CustomerUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableUpdatedAt(t *time.Time) *CustomerUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (cuo *CustomerUpdateOne) ClearUpdatedAt() *CustomerUpdateOne {
	cuo.mutation.ClearUpdatedAt()
	return cuo
}

// AddAbonementIDs adds the "abonements" edge to the Abonement entity by IDs.
func (cuo *CustomerUpdateOne) AddAbonementIDs(ids ...int) *CustomerUpdateOne {
	cuo.mutation.AddAbonementIDs(ids...)
	return cuo
}

// AddAbonements adds the "abonements" edges to the Abonement entity.
func (cuo *CustomerUpdateOne) AddAbonements(a ...*Abonement) *CustomerUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.AddAbonementIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (cuo *CustomerUpdateOne) Mutation() *CustomerMutation {
	return cuo.mutation
}

// ClearAbonements clears all "abonements" edges to the Abonement entity.
func (cuo *CustomerUpdateOne) ClearAbonements() *CustomerUpdateOne {
	cuo.mutation.ClearAbonements()
	return cuo
}

// RemoveAbonementIDs removes the "abonements" edge to Abonement entities by IDs.
func (cuo *CustomerUpdateOne) RemoveAbonementIDs(ids ...int) *CustomerUpdateOne {
	cuo.mutation.RemoveAbonementIDs(ids...)
	return cuo
}

// RemoveAbonements removes "abonements" edges to Abonement entities.
func (cuo *CustomerUpdateOne) RemoveAbonements(a ...*Abonement) *CustomerUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.RemoveAbonementIDs(ids...)
}

// Where appends a list predicates to the CustomerUpdate builder.
func (cuo *CustomerUpdateOne) Where(ps ...predicate.Customer) *CustomerUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CustomerUpdateOne) Select(field string, fields ...string) *CustomerUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Customer entity.
func (cuo *CustomerUpdateOne) Save(ctx context.Context) (*Customer, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CustomerUpdateOne) SaveX(ctx context.Context) *Customer {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CustomerUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CustomerUpdateOne) sqlSave(ctx context.Context) (_node *Customer, err error) {
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Customer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customer.FieldID)
		for _, f := range fields {
			if !customer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Keycloakid(); ok {
		_spec.SetField(customer.FieldKeycloakid, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Firstname(); ok {
		_spec.SetField(customer.FieldFirstname, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Lastname(); ok {
		_spec.SetField(customer.FieldLastname, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Licensegroups(); ok {
		_spec.SetField(customer.FieldLicensegroups, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
	}
	if cuo.mutation.CreatedAtCleared() {
		_spec.ClearField(customer.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(customer.FieldUpdatedAt, field.TypeTime)
	}
	if cuo.mutation.AbonementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedAbonementsIDs(); len(nodes) > 0 && !cuo.mutation.AbonementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AbonementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Customer{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
