// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/abonement"
	"github.com/augustin-wien/augustina-backend/ent/customer"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
}

// SetKeycloakid sets the "keycloakid" field.
func (cc *CustomerCreate) SetKeycloakid(s string) *CustomerCreate {
	cc.mutation.SetKeycloakid(s)
	return cc
}

// SetEmail sets the "email" field.
func (cc *CustomerCreate) SetEmail(s string) *CustomerCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableEmail(s *string) *CustomerCreate {
	if s != nil {
		cc.SetEmail(*s)
	}
	return cc
}

// SetFirstname sets the "firstname" field.
func (cc *CustomerCreate) SetFirstname(s string) *CustomerCreate {
	cc.mutation.SetFirstname(s)
	return cc
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableFirstname(s *string) *CustomerCreate {
	if s != nil {
		cc.SetFirstname(*s)
	}
	return cc
}

// SetLastname sets the "lastname" field.
func (cc *CustomerCreate) SetLastname(s string) *CustomerCreate {
	cc.mutation.SetLastname(s)
	return cc
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableLastname(s *string) *CustomerCreate {
	if s != nil {
		cc.SetLastname(*s)
	}
	return cc
}

// SetLicensegroups sets the "licensegroups" field.
func (cc *CustomerCreate) SetLicensegroups(s string) *CustomerCreate {
	cc.mutation.SetLicensegroups(s)
	return cc
}

// SetNillableLicensegroups sets the "licensegroups" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableLicensegroups(s *string) *CustomerCreate {
	if s != nil {
		cc.SetLicensegroups(*s)
	}
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CustomerCreate) SetCreatedAt(t time.Time) *CustomerCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableCreatedAt(t *time.Time) *CustomerCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CustomerCreate) SetUpdatedAt(t time.Time) *CustomerCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableUpdatedAt(t *time.Time) *CustomerCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CustomerCreate) SetID(i int) *CustomerCreate {
	cc.mutation.SetID(i)
	return cc
}

// AddAbonementIDs adds the "abonements" edge to the Abonement entity by IDs.
func (cc *CustomerCreate) AddAbonementIDs(ids ...int) *CustomerCreate {
	cc.mutation.AddAbonementIDs(ids...)
	return cc
}

// AddAbonements adds the "abonements" edges to the Abonement entity.
func (cc *CustomerCreate) AddAbonements(a ...*Abonement) *CustomerCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cc.AddAbonementIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (cc *CustomerCreate) Mutation() *CustomerMutation {
	return cc.mutation
}

// Save creates the Customer in the database.
func (cc *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CustomerCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CustomerCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CustomerCreate) defaults() {
	if _, ok := cc.mutation.Email(); !ok {
		v := customer.DefaultEmail
		cc.mutation.SetEmail(v)
	}
	if _, ok := cc.mutation.Firstname(); !ok {
		v := customer.DefaultFirstname
		cc.mutation.SetFirstname(v)
	}
	if _, ok := cc.mutation.Lastname(); !ok {
		v := customer.DefaultLastname
		cc.mutation.SetLastname(v)
	}
	if _, ok := cc.mutation.Licensegroups(); !ok {
		v := customer.DefaultLicensegroups
		cc.mutation.SetLicensegroups(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CustomerCreate) check() error {
	if _, ok := cc.mutation.Keycloakid(); !ok {
		return &ValidationError{Name: "keycloakid", err: errors.New(`ent: missing required field "Customer.keycloakid"`)}
	}
	if _, ok := cc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Customer.email"`)}
	}
	if _, ok := cc.mutation.Firstname(); !ok {
		return &ValidationError{Name: "firstname", err: errors.New(`ent: missing required field "Customer.firstname"`)}
	}
	if _, ok := cc.mutation.Lastname(); !ok {
		return &ValidationError{Name: "lastname", err: errors.New(`ent: missing required field "Customer.lastname"`)}
	}
	if _, ok := cc.mutation.Licensegroups(); !ok {
		return &ValidationError{Name: "licensegroups", err: errors.New(`ent: missing required field "Customer.licensegroups"`)}
	}
	if v, ok := cc.mutation.ID(); ok {
		if err := customer.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Customer.id": %w`, err)}
		}
	}
	return nil
}

func (cc *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Keycloakid(); ok {
		_spec.SetField(customer.FieldKeycloakid, field.TypeString, value)
		_node.Keycloakid = value
	}
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := cc.mutation.Firstname(); ok {
		_spec.SetField(customer.FieldFirstname, field.TypeString, value)
		_node.Firstname = value
	}
	if value, ok := cc.mutation.Lastname(); ok {
		_spec.SetField(customer.FieldLastname, field.TypeString, value)
		_node.Lastname = value
	}
	if value, ok := cc.mutation.Licensegroups(); ok {
		_spec.SetField(customer.FieldLicensegroups, field.TypeString, value)
		_node.Licensegroups = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := cc.mutation.AbonementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AbonementsTable,
			Columns: []string{customer.AbonementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(abonement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
}

// Save creates the Customer entities in the database.
func (ccb *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Customer, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
