// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/dbsettings"
)

// DBSettingsCreate is the builder for creating a DBSettings entity.
type DBSettingsCreate struct {
	config
	mutation *DBSettingsMutation
	hooks    []Hook
}

// SetIsInitialized sets the "is_initialized" field.
func (dsc *DBSettingsCreate) SetIsInitialized(b bool) *DBSettingsCreate {
	dsc.mutation.SetIsInitialized(b)
	return dsc
}

// SetID sets the "id" field.
func (dsc *DBSettingsCreate) SetID(i int) *DBSettingsCreate {
	dsc.mutation.SetID(i)
	return dsc
}

// Mutation returns the DBSettingsMutation object of the builder.
func (dsc *DBSettingsCreate) Mutation() *DBSettingsMutation {
	return dsc.mutation
}

// Save creates the DBSettings in the database.
func (dsc *DBSettingsCreate) Save(ctx context.Context) (*DBSettings, error) {
	return withHooks(ctx, dsc.sqlSave, dsc.mutation, dsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dsc *DBSettingsCreate) SaveX(ctx context.Context) *DBSettings {
	v, err := dsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dsc *DBSettingsCreate) Exec(ctx context.Context) error {
	_, err := dsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsc *DBSettingsCreate) ExecX(ctx context.Context) {
	if err := dsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dsc *DBSettingsCreate) check() error {
	if _, ok := dsc.mutation.IsInitialized(); !ok {
		return &ValidationError{Name: "is_initialized", err: errors.New(`ent: missing required field "DBSettings.is_initialized"`)}
	}
	if v, ok := dsc.mutation.ID(); ok {
		if err := dbsettings.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DBSettings.id": %w`, err)}
		}
	}
	return nil
}

func (dsc *DBSettingsCreate) sqlSave(ctx context.Context) (*DBSettings, error) {
	if err := dsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	dsc.mutation.id = &_node.ID
	dsc.mutation.done = true
	return _node, nil
}

func (dsc *DBSettingsCreate) createSpec() (*DBSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &DBSettings{config: dsc.config}
		_spec = sqlgraph.NewCreateSpec(dbsettings.Table, sqlgraph.NewFieldSpec(dbsettings.FieldID, field.TypeInt))
	)
	if id, ok := dsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dsc.mutation.IsInitialized(); ok {
		_spec.SetField(dbsettings.FieldIsInitialized, field.TypeBool, value)
		_node.IsInitialized = value
	}
	return _node, _spec
}

// DBSettingsCreateBulk is the builder for creating many DBSettings entities in bulk.
type DBSettingsCreateBulk struct {
	config
	err      error
	builders []*DBSettingsCreate
}

// Save creates the DBSettings entities in the database.
func (dscb *DBSettingsCreateBulk) Save(ctx context.Context) ([]*DBSettings, error) {
	if dscb.err != nil {
		return nil, dscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dscb.builders))
	nodes := make([]*DBSettings, len(dscb.builders))
	mutators := make([]Mutator, len(dscb.builders))
	for i := range dscb.builders {
		func(i int, root context.Context) {
			builder := dscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DBSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dscb *DBSettingsCreateBulk) SaveX(ctx context.Context) []*DBSettings {
	v, err := dscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dscb *DBSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := dscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dscb *DBSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := dscb.Exec(ctx); err != nil {
		panic(err)
	}
}
