// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/augustin-wien/augustina-backend/ent/dbsettings"
)

// DBSettings is the model entity for the DBSettings schema.
type DBSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IsInitialized holds the value of the "is_initialized" field.
	IsInitialized bool `json:"is_initialized,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DBSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dbsettings.FieldIsInitialized:
			values[i] = new(sql.NullBool)
		case dbsettings.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DBSettings fields.
func (_m *DBSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dbsettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dbsettings.FieldIsInitialized:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_initialized", values[i])
			} else if value.Valid {
				_m.IsInitialized = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DBSettings.
// This includes values selected through modifiers, order, etc.
func (_m *DBSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DBSettings.
// Note that you need to call DBSettings.Unwrap() before calling this method if this DBSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DBSettings) Update() *DBSettingsUpdateOne {
	return NewDBSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DBSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DBSettings) Unwrap() *DBSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DBSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DBSettings) String() string {
	var builder strings.Builder
	builder.WriteString("DBSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("is_initialized=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsInitialized))
	builder.WriteByte(')')
	return builder.String()
}

// DBSettingsSlice is a parsable slice of DBSettings.
type DBSettingsSlice []*DBSettings
