// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/dbsettings"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// DBSettingsDelete is the builder for deleting a DBSettings entity.
type DBSettingsDelete struct {
	config
	hooks    []Hook
	mutation *DBSettingsMutation
}

// Where appends a list predicates to the DBSettingsDelete builder.
func (dsd *DBSettingsDelete) Where(ps ...predicate.DBSettings) *DBSettingsDelete {
	dsd.mutation.Where(ps...)
	return dsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dsd *DBSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dsd.sqlExec, dsd.mutation, dsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dsd *DBSettingsDelete) ExecX(ctx context.Context) int {
	n, err := dsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dsd *DBSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dbsettings.Table, sqlgraph.NewFieldSpec(dbsettings.FieldID, field.TypeInt))
	if ps := dsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dsd.mutation.done = true
	return affected, err
}

// DBSettingsDeleteOne is the builder for deleting a single DBSettings entity.
type DBSettingsDeleteOne struct {
	dsd *DBSettingsDelete
}

// Where appends a list predicates to the DBSettingsDelete builder.
func (dsdo *DBSettingsDeleteOne) Where(ps ...predicate.DBSettings) *DBSettingsDeleteOne {
	dsdo.dsd.mutation.Where(ps...)
	return dsdo
}

// Exec executes the deletion query.
func (dsdo *DBSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := dsdo.dsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dbsettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dsdo *DBSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := dsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
