// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/mailtemplate"
)

// MailTemplateCreate is the builder for creating a MailTemplate entity.
type MailTemplateCreate struct {
	config
	mutation *MailTemplateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MailTemplateCreate) SetName(v string) *MailTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *MailTemplateCreate) SetSubject(v string) *MailTemplateCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *MailTemplateCreate) SetBody(v string) *MailTemplateCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MailTemplateCreate) SetCreatedAt(v time.Time) *MailTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MailTemplateCreate) SetUpdatedAt(v time.Time) *MailTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MailTemplateCreate) SetID(v int) *MailTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MailTemplateMutation object of the builder.
func (_c *MailTemplateCreate) Mutation() *MailTemplateMutation {
	return _c.mutation
}

// Save creates the MailTemplate in the database.
func (_c *MailTemplateCreate) Save(ctx context.Context) (*MailTemplate, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailTemplateCreate) SaveX(ctx context.Context) *MailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MailTemplate.name"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "MailTemplate.subject"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "MailTemplate.body"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MailTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MailTemplate.updated_at"`)}
	}
	return nil
}

func (_c *MailTemplateCreate) sqlSave(ctx context.Context) (*MailTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailTemplateCreate) createSpec() (*MailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &MailTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailtemplate.Table, sqlgraph.NewFieldSpec(mailtemplate.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(mailtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(mailtemplate.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(mailtemplate.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mailtemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mailtemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MailTemplateCreateBulk is the builder for creating many MailTemplate entities in bulk.
type MailTemplateCreateBulk struct {
	config
	err      error
	builders []*MailTemplateCreate
}

// Save creates the MailTemplate entities in the database.
func (_c *MailTemplateCreateBulk) Save(ctx context.Context) ([]*MailTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailTemplateCreateBulk) SaveX(ctx context.Context) []*MailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
