// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/augustin-wien/augustina-backend/ent/account"
	"github.com/augustin-wien/augustina-backend/ent/item"
	"github.com/augustin-wien/augustina-backend/ent/order"
	"github.com/augustin-wien/augustina-backend/ent/orderentry"
)

// OrderEntry is the model entity for the OrderEntry schema.
type OrderEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// Price holds the value of the "price" field.
	Price int `json:"price,omitempty"`
	// IsSale holds the value of the "is_sale" field.
	IsSale bool `json:"is_sale,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID int `json:"item_id,omitempty"`
	// SenderID holds the value of the "sender_id" field.
	SenderID int `json:"sender_id,omitempty"`
	// ReceiverID holds the value of the "receiver_id" field.
	ReceiverID int `json:"receiver_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int `json:"order_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderEntryQuery when eager-loading is set.
	Edges        OrderEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderEntryEdges holds the relations/edges for other nodes in the graph.
type OrderEntryEdges struct {
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *Account `json:"sender,omitempty"`
	// Receiver holds the value of the receiver edge.
	Receiver *Account `json:"receiver,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEntryEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEntryEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEntryEdges) SenderOrErr() (*Account, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// ReceiverOrErr returns the Receiver value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEntryEdges) ReceiverOrErr() (*Account, error) {
	if e.Receiver != nil {
		return e.Receiver, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "receiver"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderentry.FieldIsSale:
			values[i] = new(sql.NullBool)
		case orderentry.FieldID, orderentry.FieldQuantity, orderentry.FieldPrice, orderentry.FieldItemID, orderentry.FieldSenderID, orderentry.FieldReceiverID, orderentry.FieldOrderID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderEntry fields.
func (oe *OrderEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			oe.ID = int(value.Int64)
		case orderentry.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				oe.Quantity = int(value.Int64)
			}
		case orderentry.FieldPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				oe.Price = int(value.Int64)
			}
		case orderentry.FieldIsSale:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_sale", values[i])
			} else if value.Valid {
				oe.IsSale = value.Bool
			}
		case orderentry.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				oe.ItemID = int(value.Int64)
			}
		case orderentry.FieldSenderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				oe.SenderID = int(value.Int64)
			}
		case orderentry.FieldReceiverID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receiver_id", values[i])
			} else if value.Valid {
				oe.ReceiverID = int(value.Int64)
			}
		case orderentry.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				oe.OrderID = int(value.Int64)
			}
		default:
			oe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderEntry.
// This includes values selected through modifiers, order, etc.
func (oe *OrderEntry) Value(name string) (ent.Value, error) {
	return oe.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the OrderEntry entity.
func (oe *OrderEntry) QueryOrder() *OrderQuery {
	return NewOrderEntryClient(oe.config).QueryOrder(oe)
}

// QueryItem queries the "item" edge of the OrderEntry entity.
func (oe *OrderEntry) QueryItem() *ItemQuery {
	return NewOrderEntryClient(oe.config).QueryItem(oe)
}

// QuerySender queries the "sender" edge of the OrderEntry entity.
func (oe *OrderEntry) QuerySender() *AccountQuery {
	return NewOrderEntryClient(oe.config).QuerySender(oe)
}

// QueryReceiver queries the "receiver" edge of the OrderEntry entity.
func (oe *OrderEntry) QueryReceiver() *AccountQuery {
	return NewOrderEntryClient(oe.config).QueryReceiver(oe)
}

// Update returns a builder for updating this OrderEntry.
// Note that you need to call OrderEntry.Unwrap() before calling this method if this OrderEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (oe *OrderEntry) Update() *OrderEntryUpdateOne {
	return NewOrderEntryClient(oe.config).UpdateOne(oe)
}

// Unwrap unwraps the OrderEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oe *OrderEntry) Unwrap() *OrderEntry {
	_tx, ok := oe.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderEntry is not a transactional entity")
	}
	oe.config.driver = _tx.drv
	return oe
}

// String implements the fmt.Stringer.
func (oe *OrderEntry) String() string {
	var builder strings.Builder
	builder.WriteString("OrderEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", oe.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", oe.Quantity))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", oe.Price))
	builder.WriteString(", ")
	builder.WriteString("is_sale=")
	builder.WriteString(fmt.Sprintf("%v", oe.IsSale))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", oe.ItemID))
	builder.WriteString(", ")
	builder.WriteString("sender_id=")
	builder.WriteString(fmt.Sprintf("%v", oe.SenderID))
	builder.WriteString(", ")
	builder.WriteString("receiver_id=")
	builder.WriteString(fmt.Sprintf("%v", oe.ReceiverID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", oe.OrderID))
	builder.WriteByte(')')
	return builder.String()
}

// OrderEntries is a parsable slice of OrderEntry.
type OrderEntries []*OrderEntry
