// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/order"
	"github.com/augustin-wien/augustina-backend/ent/payment"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetTimestamp sets the "timestamp" field.
func (pu *PaymentUpdate) SetTimestamp(t time.Time) *PaymentUpdate {
	pu.mutation.SetTimestamp(t)
	return pu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableTimestamp(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetTimestamp(*t)
	}
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PaymentUpdate) SetAmount(i int) *PaymentUpdate {
	pu.mutation.ResetAmount()
	pu.mutation.SetAmount(i)
	return pu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableAmount(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetAmount(*i)
	}
	return pu
}

// AddAmount adds i to the "amount" field.
func (pu *PaymentUpdate) AddAmount(i int) *PaymentUpdate {
	pu.mutation.AddAmount(i)
	return pu
}

// SetAuthorizedBy sets the "authorized_by" field.
func (pu *PaymentUpdate) SetAuthorizedBy(s string) *PaymentUpdate {
	pu.mutation.SetAuthorizedBy(s)
	return pu
}

// SetNillableAuthorizedBy sets the "authorized_by" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableAuthorizedBy(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetAuthorizedBy(*s)
	}
	return pu
}

// SetIsSale sets the "is_sale" field.
func (pu *PaymentUpdate) SetIsSale(b bool) *PaymentUpdate {
	pu.mutation.SetIsSale(b)
	return pu
}

// SetNillableIsSale sets the "is_sale" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableIsSale(b *bool) *PaymentUpdate {
	if b != nil {
		pu.SetIsSale(*b)
	}
	return pu
}

// SetQuantity sets the "quantity" field.
func (pu *PaymentUpdate) SetQuantity(i int) *PaymentUpdate {
	pu.mutation.ResetQuantity()
	pu.mutation.SetQuantity(i)
	return pu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableQuantity(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetQuantity(*i)
	}
	return pu
}

// AddQuantity adds i to the "quantity" field.
func (pu *PaymentUpdate) AddQuantity(i int) *PaymentUpdate {
	pu.mutation.AddQuantity(i)
	return pu
}

// SetPrice sets the "price" field.
func (pu *PaymentUpdate) SetPrice(i int) *PaymentUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(i)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePrice(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetPrice(*i)
	}
	return pu
}

// AddPrice adds i to the "price" field.
func (pu *PaymentUpdate) AddPrice(i int) *PaymentUpdate {
	pu.mutation.AddPrice(i)
	return pu
}

// SetSenderID sets the "sender_id" field.
func (pu *PaymentUpdate) SetSenderID(i int) *PaymentUpdate {
	pu.mutation.ResetSenderID()
	pu.mutation.SetSenderID(i)
	return pu
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableSenderID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetSenderID(*i)
	}
	return pu
}

// AddSenderID adds i to the "sender_id" field.
func (pu *PaymentUpdate) AddSenderID(i int) *PaymentUpdate {
	pu.mutation.AddSenderID(i)
	return pu
}

// SetReceiverID sets the "receiver_id" field.
func (pu *PaymentUpdate) SetReceiverID(i int) *PaymentUpdate {
	pu.mutation.ResetReceiverID()
	pu.mutation.SetReceiverID(i)
	return pu
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableReceiverID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetReceiverID(*i)
	}
	return pu
}

// AddReceiverID adds i to the "receiver_id" field.
func (pu *PaymentUpdate) AddReceiverID(i int) *PaymentUpdate {
	pu.mutation.AddReceiverID(i)
	return pu
}

// SetOrderID sets the "order_id" field.
func (pu *PaymentUpdate) SetOrderID(i int) *PaymentUpdate {
	pu.mutation.SetOrderID(i)
	return pu
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOrderID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetOrderID(*i)
	}
	return pu
}

// ClearOrderID clears the value of the "order_id" field.
func (pu *PaymentUpdate) ClearOrderID() *PaymentUpdate {
	pu.mutation.ClearOrderID()
	return pu
}

// SetOrderEntryID sets the "order_entry_id" field.
func (pu *PaymentUpdate) SetOrderEntryID(i int) *PaymentUpdate {
	pu.mutation.ResetOrderEntryID()
	pu.mutation.SetOrderEntryID(i)
	return pu
}

// SetNillableOrderEntryID sets the "order_entry_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOrderEntryID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetOrderEntryID(*i)
	}
	return pu
}

// AddOrderEntryID adds i to the "order_entry_id" field.
func (pu *PaymentUpdate) AddOrderEntryID(i int) *PaymentUpdate {
	pu.mutation.AddOrderEntryID(i)
	return pu
}

// ClearOrderEntryID clears the value of the "order_entry_id" field.
func (pu *PaymentUpdate) ClearOrderEntryID() *PaymentUpdate {
	pu.mutation.ClearOrderEntryID()
	return pu
}

// SetItemID sets the "item_id" field.
func (pu *PaymentUpdate) SetItemID(i int) *PaymentUpdate {
	pu.mutation.ResetItemID()
	pu.mutation.SetItemID(i)
	return pu
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableItemID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetItemID(*i)
	}
	return pu
}

// AddItemID adds i to the "item_id" field.
func (pu *PaymentUpdate) AddItemID(i int) *PaymentUpdate {
	pu.mutation.AddItemID(i)
	return pu
}

// ClearItemID clears the value of the "item_id" field.
func (pu *PaymentUpdate) ClearItemID() *PaymentUpdate {
	pu.mutation.ClearItemID()
	return pu
}

// SetPayoutID sets the "payout_id" field.
func (pu *PaymentUpdate) SetPayoutID(i int) *PaymentUpdate {
	pu.mutation.SetPayoutID(i)
	return pu
}

// SetNillablePayoutID sets the "payout_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePayoutID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetPayoutID(*i)
	}
	return pu
}

// ClearPayoutID clears the value of the "payout_id" field.
func (pu *PaymentUpdate) ClearPayoutID() *PaymentUpdate {
	pu.mutation.ClearPayoutID()
	return pu
}

// SetOrder sets the "order" edge to the Order entity.
func (pu *PaymentUpdate) SetOrder(o *Order) *PaymentUpdate {
	return pu.SetOrderID(o.ID)
}

// SetParentID sets the "parent" edge to the Payment entity by ID.
func (pu *PaymentUpdate) SetParentID(id int) *PaymentUpdate {
	pu.mutation.SetParentID(id)
	return pu
}

// SetNillableParentID sets the "parent" edge to the Payment entity by ID if the given value is not nil.
func (pu *PaymentUpdate) SetNillableParentID(id *int) *PaymentUpdate {
	if id != nil {
		pu = pu.SetParentID(*id)
	}
	return pu
}

// SetParent sets the "parent" edge to the Payment entity.
func (pu *PaymentUpdate) SetParent(p *Payment) *PaymentUpdate {
	return pu.SetParentID(p.ID)
}

// AddChildIDs adds the "children" edge to the Payment entity by IDs.
func (pu *PaymentUpdate) AddChildIDs(ids ...int) *PaymentUpdate {
	pu.mutation.AddChildIDs(ids...)
	return pu
}

// AddChildren adds the "children" edges to the Payment entity.
func (pu *PaymentUpdate) AddChildren(p ...*Payment) *PaymentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddChildIDs(ids...)
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (pu *PaymentUpdate) ClearOrder() *PaymentUpdate {
	pu.mutation.ClearOrder()
	return pu
}

// ClearParent clears the "parent" edge to the Payment entity.
func (pu *PaymentUpdate) ClearParent() *PaymentUpdate {
	pu.mutation.ClearParent()
	return pu
}

// ClearChildren clears all "children" edges to the Payment entity.
func (pu *PaymentUpdate) ClearChildren() *PaymentUpdate {
	pu.mutation.ClearChildren()
	return pu
}

// RemoveChildIDs removes the "children" edge to Payment entities by IDs.
func (pu *PaymentUpdate) RemoveChildIDs(ids ...int) *PaymentUpdate {
	pu.mutation.RemoveChildIDs(ids...)
	return pu
}

// RemoveChildren removes "children" edges to Payment entities.
func (pu *PaymentUpdate) RemoveChildren(p ...*Payment) *PaymentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Timestamp(); ok {
		_spec.SetField(payment.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AuthorizedBy(); ok {
		_spec.SetField(payment.FieldAuthorizedBy, field.TypeString, value)
	}
	if value, ok := pu.mutation.IsSale(); ok {
		_spec.SetField(payment.FieldIsSale, field.TypeBool, value)
	}
	if value, ok := pu.mutation.Quantity(); ok {
		_spec.SetField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedQuantity(); ok {
		_spec.AddField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := pu.mutation.SenderID(); ok {
		_spec.SetField(payment.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedSenderID(); ok {
		_spec.AddField(payment.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.ReceiverID(); ok {
		_spec.SetField(payment.FieldReceiverID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedReceiverID(); ok {
		_spec.AddField(payment.FieldReceiverID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.OrderEntryID(); ok {
		_spec.SetField(payment.FieldOrderEntryID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedOrderEntryID(); ok {
		_spec.AddField(payment.FieldOrderEntryID, field.TypeInt, value)
	}
	if pu.mutation.OrderEntryIDCleared() {
		_spec.ClearField(payment.FieldOrderEntryID, field.TypeInt)
	}
	if value, ok := pu.mutation.ItemID(); ok {
		_spec.SetField(payment.FieldItemID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedItemID(); ok {
		_spec.AddField(payment.FieldItemID, field.TypeInt, value)
	}
	if pu.mutation.ItemIDCleared() {
		_spec.ClearField(payment.FieldItemID, field.TypeInt)
	}
	if pu.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.OrderTable,
			Columns: []string{payment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.OrderTable,
			Columns: []string{payment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.ParentTable,
			Columns: []string{payment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.ParentTable,
			Columns: []string{payment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !pu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetTimestamp sets the "timestamp" field.
func (puo *PaymentUpdateOne) SetTimestamp(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetTimestamp(t)
	return puo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableTimestamp(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetTimestamp(*t)
	}
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PaymentUpdateOne) SetAmount(i int) *PaymentUpdateOne {
	puo.mutation.ResetAmount()
	puo.mutation.SetAmount(i)
	return puo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableAmount(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetAmount(*i)
	}
	return puo
}

// AddAmount adds i to the "amount" field.
func (puo *PaymentUpdateOne) AddAmount(i int) *PaymentUpdateOne {
	puo.mutation.AddAmount(i)
	return puo
}

// SetAuthorizedBy sets the "authorized_by" field.
func (puo *PaymentUpdateOne) SetAuthorizedBy(s string) *PaymentUpdateOne {
	puo.mutation.SetAuthorizedBy(s)
	return puo
}

// SetNillableAuthorizedBy sets the "authorized_by" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableAuthorizedBy(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetAuthorizedBy(*s)
	}
	return puo
}

// SetIsSale sets the "is_sale" field.
func (puo *PaymentUpdateOne) SetIsSale(b bool) *PaymentUpdateOne {
	puo.mutation.SetIsSale(b)
	return puo
}

// SetNillableIsSale sets the "is_sale" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableIsSale(b *bool) *PaymentUpdateOne {
	if b != nil {
		puo.SetIsSale(*b)
	}
	return puo
}

// SetQuantity sets the "quantity" field.
func (puo *PaymentUpdateOne) SetQuantity(i int) *PaymentUpdateOne {
	puo.mutation.ResetQuantity()
	puo.mutation.SetQuantity(i)
	return puo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableQuantity(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetQuantity(*i)
	}
	return puo
}

// AddQuantity adds i to the "quantity" field.
func (puo *PaymentUpdateOne) AddQuantity(i int) *PaymentUpdateOne {
	puo.mutation.AddQuantity(i)
	return puo
}

// SetPrice sets the "price" field.
func (puo *PaymentUpdateOne) SetPrice(i int) *PaymentUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(i)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePrice(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetPrice(*i)
	}
	return puo
}

// AddPrice adds i to the "price" field.
func (puo *PaymentUpdateOne) AddPrice(i int) *PaymentUpdateOne {
	puo.mutation.AddPrice(i)
	return puo
}

// SetSenderID sets the "sender_id" field.
func (puo *PaymentUpdateOne) SetSenderID(i int) *PaymentUpdateOne {
	puo.mutation.ResetSenderID()
	puo.mutation.SetSenderID(i)
	return puo
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableSenderID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetSenderID(*i)
	}
	return puo
}

// AddSenderID adds i to the "sender_id" field.
func (puo *PaymentUpdateOne) AddSenderID(i int) *PaymentUpdateOne {
	puo.mutation.AddSenderID(i)
	return puo
}

// SetReceiverID sets the "receiver_id" field.
func (puo *PaymentUpdateOne) SetReceiverID(i int) *PaymentUpdateOne {
	puo.mutation.ResetReceiverID()
	puo.mutation.SetReceiverID(i)
	return puo
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableReceiverID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetReceiverID(*i)
	}
	return puo
}

// AddReceiverID adds i to the "receiver_id" field.
func (puo *PaymentUpdateOne) AddReceiverID(i int) *PaymentUpdateOne {
	puo.mutation.AddReceiverID(i)
	return puo
}

// SetOrderID sets the "order_id" field.
func (puo *PaymentUpdateOne) SetOrderID(i int) *PaymentUpdateOne {
	puo.mutation.SetOrderID(i)
	return puo
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOrderID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetOrderID(*i)
	}
	return puo
}

// ClearOrderID clears the value of the "order_id" field.
func (puo *PaymentUpdateOne) ClearOrderID() *PaymentUpdateOne {
	puo.mutation.ClearOrderID()
	return puo
}

// SetOrderEntryID sets the "order_entry_id" field.
func (puo *PaymentUpdateOne) SetOrderEntryID(i int) *PaymentUpdateOne {
	puo.mutation.ResetOrderEntryID()
	puo.mutation.SetOrderEntryID(i)
	return puo
}

// SetNillableOrderEntryID sets the "order_entry_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOrderEntryID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetOrderEntryID(*i)
	}
	return puo
}

// AddOrderEntryID adds i to the "order_entry_id" field.
func (puo *PaymentUpdateOne) AddOrderEntryID(i int) *PaymentUpdateOne {
	puo.mutation.AddOrderEntryID(i)
	return puo
}

// ClearOrderEntryID clears the value of the "order_entry_id" field.
func (puo *PaymentUpdateOne) ClearOrderEntryID() *PaymentUpdateOne {
	puo.mutation.ClearOrderEntryID()
	return puo
}

// SetItemID sets the "item_id" field.
func (puo *PaymentUpdateOne) SetItemID(i int) *PaymentUpdateOne {
	puo.mutation.ResetItemID()
	puo.mutation.SetItemID(i)
	return puo
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableItemID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetItemID(*i)
	}
	return puo
}

// AddItemID adds i to the "item_id" field.
func (puo *PaymentUpdateOne) AddItemID(i int) *PaymentUpdateOne {
	puo.mutation.AddItemID(i)
	return puo
}

// ClearItemID clears the value of the "item_id" field.
func (puo *PaymentUpdateOne) ClearItemID() *PaymentUpdateOne {
	puo.mutation.ClearItemID()
	return puo
}

// SetPayoutID sets the "payout_id" field.
func (puo *PaymentUpdateOne) SetPayoutID(i int) *PaymentUpdateOne {
	puo.mutation.SetPayoutID(i)
	return puo
}

// SetNillablePayoutID sets the "payout_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePayoutID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetPayoutID(*i)
	}
	return puo
}

// ClearPayoutID clears the value of the "payout_id" field.
func (puo *PaymentUpdateOne) ClearPayoutID() *PaymentUpdateOne {
	puo.mutation.ClearPayoutID()
	return puo
}

// SetOrder sets the "order" edge to the Order entity.
func (puo *PaymentUpdateOne) SetOrder(o *Order) *PaymentUpdateOne {
	return puo.SetOrderID(o.ID)
}

// SetParentID sets the "parent" edge to the Payment entity by ID.
func (puo *PaymentUpdateOne) SetParentID(id int) *PaymentUpdateOne {
	puo.mutation.SetParentID(id)
	return puo
}

// SetNillableParentID sets the "parent" edge to the Payment entity by ID if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableParentID(id *int) *PaymentUpdateOne {
	if id != nil {
		puo = puo.SetParentID(*id)
	}
	return puo
}

// SetParent sets the "parent" edge to the Payment entity.
func (puo *PaymentUpdateOne) SetParent(p *Payment) *PaymentUpdateOne {
	return puo.SetParentID(p.ID)
}

// AddChildIDs adds the "children" edge to the Payment entity by IDs.
func (puo *PaymentUpdateOne) AddChildIDs(ids ...int) *PaymentUpdateOne {
	puo.mutation.AddChildIDs(ids...)
	return puo
}

// AddChildren adds the "children" edges to the Payment entity.
func (puo *PaymentUpdateOne) AddChildren(p ...*Payment) *PaymentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddChildIDs(ids...)
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (puo *PaymentUpdateOne) ClearOrder() *PaymentUpdateOne {
	puo.mutation.ClearOrder()
	return puo
}

// ClearParent clears the "parent" edge to the Payment entity.
func (puo *PaymentUpdateOne) ClearParent() *PaymentUpdateOne {
	puo.mutation.ClearParent()
	return puo
}

// ClearChildren clears all "children" edges to the Payment entity.
func (puo *PaymentUpdateOne) ClearChildren() *PaymentUpdateOne {
	puo.mutation.ClearChildren()
	return puo
}

// RemoveChildIDs removes the "children" edge to Payment entities by IDs.
func (puo *PaymentUpdateOne) RemoveChildIDs(ids ...int) *PaymentUpdateOne {
	puo.mutation.RemoveChildIDs(ids...)
	return puo
}

// RemoveChildren removes "children" edges to Payment entities.
func (puo *PaymentUpdateOne) RemoveChildren(p ...*Payment) *PaymentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the PaymentUpdate builder.
func (puo *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Payment entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Timestamp(); ok {
		_spec.SetField(payment.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AuthorizedBy(); ok {
		_spec.SetField(payment.FieldAuthorizedBy, field.TypeString, value)
	}
	if value, ok := puo.mutation.IsSale(); ok {
		_spec.SetField(payment.FieldIsSale, field.TypeBool, value)
	}
	if value, ok := puo.mutation.Quantity(); ok {
		_spec.SetField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedQuantity(); ok {
		_spec.AddField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := puo.mutation.SenderID(); ok {
		_spec.SetField(payment.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedSenderID(); ok {
		_spec.AddField(payment.FieldSenderID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.ReceiverID(); ok {
		_spec.SetField(payment.FieldReceiverID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedReceiverID(); ok {
		_spec.AddField(payment.FieldReceiverID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.OrderEntryID(); ok {
		_spec.SetField(payment.FieldOrderEntryID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedOrderEntryID(); ok {
		_spec.AddField(payment.FieldOrderEntryID, field.TypeInt, value)
	}
	if puo.mutation.OrderEntryIDCleared() {
		_spec.ClearField(payment.FieldOrderEntryID, field.TypeInt)
	}
	if value, ok := puo.mutation.ItemID(); ok {
		_spec.SetField(payment.FieldItemID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedItemID(); ok {
		_spec.AddField(payment.FieldItemID, field.TypeInt, value)
	}
	if puo.mutation.ItemIDCleared() {
		_spec.ClearField(payment.FieldItemID, field.TypeInt)
	}
	if puo.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.OrderTable,
			Columns: []string{payment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.OrderTable,
			Columns: []string{payment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.ParentTable,
			Columns: []string{payment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.ParentTable,
			Columns: []string{payment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !puo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   payment.ChildrenTable,
			Columns: []string{payment.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
