// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/pdfdownload"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// PDFDownloadUpdate is the builder for updating PDFDownload entities.
type PDFDownloadUpdate struct {
	config
	hooks    []Hook
	mutation *PDFDownloadMutation
}

// Where appends a list predicates to the PDFDownloadUpdate builder.
func (pdu *PDFDownloadUpdate) Where(ps ...predicate.PDFDownload) *PDFDownloadUpdate {
	pdu.mutation.Where(ps...)
	return pdu
}

// SetLinkID sets the "link_id" field.
func (pdu *PDFDownloadUpdate) SetLinkID(s string) *PDFDownloadUpdate {
	pdu.mutation.SetLinkID(s)
	return pdu
}

// SetNillableLinkID sets the "link_id" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableLinkID(s *string) *PDFDownloadUpdate {
	if s != nil {
		pdu.SetLinkID(*s)
	}
	return pdu
}

// SetPdfID sets the "pdf_id" field.
func (pdu *PDFDownloadUpdate) SetPdfID(i int) *PDFDownloadUpdate {
	pdu.mutation.ResetPdfID()
	pdu.mutation.SetPdfID(i)
	return pdu
}

// SetNillablePdfID sets the "pdf_id" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillablePdfID(i *int) *PDFDownloadUpdate {
	if i != nil {
		pdu.SetPdfID(*i)
	}
	return pdu
}

// AddPdfID adds i to the "pdf_id" field.
func (pdu *PDFDownloadUpdate) AddPdfID(i int) *PDFDownloadUpdate {
	pdu.mutation.AddPdfID(i)
	return pdu
}

// SetTimestamp sets the "timestamp" field.
func (pdu *PDFDownloadUpdate) SetTimestamp(t time.Time) *PDFDownloadUpdate {
	pdu.mutation.SetTimestamp(t)
	return pdu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableTimestamp(t *time.Time) *PDFDownloadUpdate {
	if t != nil {
		pdu.SetTimestamp(*t)
	}
	return pdu
}

// SetEmailSent sets the "email_sent" field.
func (pdu *PDFDownloadUpdate) SetEmailSent(b bool) *PDFDownloadUpdate {
	pdu.mutation.SetEmailSent(b)
	return pdu
}

// SetNillableEmailSent sets the "email_sent" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableEmailSent(b *bool) *PDFDownloadUpdate {
	if b != nil {
		pdu.SetEmailSent(*b)
	}
	return pdu
}

// SetLastDownload sets the "last_download" field.
func (pdu *PDFDownloadUpdate) SetLastDownload(t time.Time) *PDFDownloadUpdate {
	pdu.mutation.SetLastDownload(t)
	return pdu
}

// SetNillableLastDownload sets the "last_download" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableLastDownload(t *time.Time) *PDFDownloadUpdate {
	if t != nil {
		pdu.SetLastDownload(*t)
	}
	return pdu
}

// ClearLastDownload clears the value of the "last_download" field.
func (pdu *PDFDownloadUpdate) ClearLastDownload() *PDFDownloadUpdate {
	pdu.mutation.ClearLastDownload()
	return pdu
}

// SetDownloadCount sets the "download_count" field.
func (pdu *PDFDownloadUpdate) SetDownloadCount(i int) *PDFDownloadUpdate {
	pdu.mutation.ResetDownloadCount()
	pdu.mutation.SetDownloadCount(i)
	return pdu
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableDownloadCount(i *int) *PDFDownloadUpdate {
	if i != nil {
		pdu.SetDownloadCount(*i)
	}
	return pdu
}

// AddDownloadCount adds i to the "download_count" field.
func (pdu *PDFDownloadUpdate) AddDownloadCount(i int) *PDFDownloadUpdate {
	pdu.mutation.AddDownloadCount(i)
	return pdu
}

// SetOrderID sets the "order_id" field.
func (pdu *PDFDownloadUpdate) SetOrderID(i int) *PDFDownloadUpdate {
	pdu.mutation.ResetOrderID()
	pdu.mutation.SetOrderID(i)
	return pdu
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableOrderID(i *int) *PDFDownloadUpdate {
	if i != nil {
		pdu.SetOrderID(*i)
	}
	return pdu
}

// AddOrderID adds i to the "order_id" field.
func (pdu *PDFDownloadUpdate) AddOrderID(i int) *PDFDownloadUpdate {
	pdu.mutation.AddOrderID(i)
	return pdu
}

// ClearOrderID clears the value of the "order_id" field.
func (pdu *PDFDownloadUpdate) ClearOrderID() *PDFDownloadUpdate {
	pdu.mutation.ClearOrderID()
	return pdu
}

// SetItemID sets the "item_id" field.
func (pdu *PDFDownloadUpdate) SetItemID(i int) *PDFDownloadUpdate {
	pdu.mutation.ResetItemID()
	pdu.mutation.SetItemID(i)
	return pdu
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (pdu *PDFDownloadUpdate) SetNillableItemID(i *int) *PDFDownloadUpdate {
	if i != nil {
		pdu.SetItemID(*i)
	}
	return pdu
}

// AddItemID adds i to the "item_id" field.
func (pdu *PDFDownloadUpdate) AddItemID(i int) *PDFDownloadUpdate {
	pdu.mutation.AddItemID(i)
	return pdu
}

// ClearItemID clears the value of the "item_id" field.
func (pdu *PDFDownloadUpdate) ClearItemID() *PDFDownloadUpdate {
	pdu.mutation.ClearItemID()
	return pdu
}

// Mutation returns the PDFDownloadMutation object of the builder.
func (pdu *PDFDownloadUpdate) Mutation() *PDFDownloadMutation {
	return pdu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pdu *PDFDownloadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pdu.sqlSave, pdu.mutation, pdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pdu *PDFDownloadUpdate) SaveX(ctx context.Context) int {
	affected, err := pdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pdu *PDFDownloadUpdate) Exec(ctx context.Context) error {
	_, err := pdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdu *PDFDownloadUpdate) ExecX(ctx context.Context) {
	if err := pdu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pdu *PDFDownloadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pdfdownload.Table, pdfdownload.Columns, sqlgraph.NewFieldSpec(pdfdownload.FieldID, field.TypeInt))
	if ps := pdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pdu.mutation.LinkID(); ok {
		_spec.SetField(pdfdownload.FieldLinkID, field.TypeString, value)
	}
	if value, ok := pdu.mutation.PdfID(); ok {
		_spec.SetField(pdfdownload.FieldPdfID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedPdfID(); ok {
		_spec.AddField(pdfdownload.FieldPdfID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.Timestamp(); ok {
		_spec.SetField(pdfdownload.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.EmailSent(); ok {
		_spec.SetField(pdfdownload.FieldEmailSent, field.TypeBool, value)
	}
	if value, ok := pdu.mutation.LastDownload(); ok {
		_spec.SetField(pdfdownload.FieldLastDownload, field.TypeTime, value)
	}
	if pdu.mutation.LastDownloadCleared() {
		_spec.ClearField(pdfdownload.FieldLastDownload, field.TypeTime)
	}
	if value, ok := pdu.mutation.DownloadCount(); ok {
		_spec.SetField(pdfdownload.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedDownloadCount(); ok {
		_spec.AddField(pdfdownload.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.OrderID(); ok {
		_spec.SetField(pdfdownload.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedOrderID(); ok {
		_spec.AddField(pdfdownload.FieldOrderID, field.TypeInt, value)
	}
	if pdu.mutation.OrderIDCleared() {
		_spec.ClearField(pdfdownload.FieldOrderID, field.TypeInt)
	}
	if value, ok := pdu.mutation.ItemID(); ok {
		_spec.SetField(pdfdownload.FieldItemID, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedItemID(); ok {
		_spec.AddField(pdfdownload.FieldItemID, field.TypeInt, value)
	}
	if pdu.mutation.ItemIDCleared() {
		_spec.ClearField(pdfdownload.FieldItemID, field.TypeInt)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pdfdownload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pdu.mutation.done = true
	return n, nil
}

// PDFDownloadUpdateOne is the builder for updating a single PDFDownload entity.
type PDFDownloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PDFDownloadMutation
}

// SetLinkID sets the "link_id" field.
func (pduo *PDFDownloadUpdateOne) SetLinkID(s string) *PDFDownloadUpdateOne {
	pduo.mutation.SetLinkID(s)
	return pduo
}

// SetNillableLinkID sets the "link_id" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableLinkID(s *string) *PDFDownloadUpdateOne {
	if s != nil {
		pduo.SetLinkID(*s)
	}
	return pduo
}

// SetPdfID sets the "pdf_id" field.
func (pduo *PDFDownloadUpdateOne) SetPdfID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.ResetPdfID()
	pduo.mutation.SetPdfID(i)
	return pduo
}

// SetNillablePdfID sets the "pdf_id" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillablePdfID(i *int) *PDFDownloadUpdateOne {
	if i != nil {
		pduo.SetPdfID(*i)
	}
	return pduo
}

// AddPdfID adds i to the "pdf_id" field.
func (pduo *PDFDownloadUpdateOne) AddPdfID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.AddPdfID(i)
	return pduo
}

// SetTimestamp sets the "timestamp" field.
func (pduo *PDFDownloadUpdateOne) SetTimestamp(t time.Time) *PDFDownloadUpdateOne {
	pduo.mutation.SetTimestamp(t)
	return pduo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableTimestamp(t *time.Time) *PDFDownloadUpdateOne {
	if t != nil {
		pduo.SetTimestamp(*t)
	}
	return pduo
}

// SetEmailSent sets the "email_sent" field.
func (pduo *PDFDownloadUpdateOne) SetEmailSent(b bool) *PDFDownloadUpdateOne {
	pduo.mutation.SetEmailSent(b)
	return pduo
}

// SetNillableEmailSent sets the "email_sent" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableEmailSent(b *bool) *PDFDownloadUpdateOne {
	if b != nil {
		pduo.SetEmailSent(*b)
	}
	return pduo
}

// SetLastDownload sets the "last_download" field.
func (pduo *PDFDownloadUpdateOne) SetLastDownload(t time.Time) *PDFDownloadUpdateOne {
	pduo.mutation.SetLastDownload(t)
	return pduo
}

// SetNillableLastDownload sets the "last_download" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableLastDownload(t *time.Time) *PDFDownloadUpdateOne {
	if t != nil {
		pduo.SetLastDownload(*t)
	}
	return pduo
}

// ClearLastDownload clears the value of the "last_download" field.
func (pduo *PDFDownloadUpdateOne) ClearLastDownload() *PDFDownloadUpdateOne {
	pduo.mutation.ClearLastDownload()
	return pduo
}

// SetDownloadCount sets the "download_count" field.
func (pduo *PDFDownloadUpdateOne) SetDownloadCount(i int) *PDFDownloadUpdateOne {
	pduo.mutation.ResetDownloadCount()
	pduo.mutation.SetDownloadCount(i)
	return pduo
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableDownloadCount(i *int) *PDFDownloadUpdateOne {
	if i != nil {
		pduo.SetDownloadCount(*i)
	}
	return pduo
}

// AddDownloadCount adds i to the "download_count" field.
func (pduo *PDFDownloadUpdateOne) AddDownloadCount(i int) *PDFDownloadUpdateOne {
	pduo.mutation.AddDownloadCount(i)
	return pduo
}

// SetOrderID sets the "order_id" field.
func (pduo *PDFDownloadUpdateOne) SetOrderID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.ResetOrderID()
	pduo.mutation.SetOrderID(i)
	return pduo
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableOrderID(i *int) *PDFDownloadUpdateOne {
	if i != nil {
		pduo.SetOrderID(*i)
	}
	return pduo
}

// AddOrderID adds i to the "order_id" field.
func (pduo *PDFDownloadUpdateOne) AddOrderID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.AddOrderID(i)
	return pduo
}

// ClearOrderID clears the value of the "order_id" field.
func (pduo *PDFDownloadUpdateOne) ClearOrderID() *PDFDownloadUpdateOne {
	pduo.mutation.ClearOrderID()
	return pduo
}

// SetItemID sets the "item_id" field.
func (pduo *PDFDownloadUpdateOne) SetItemID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.ResetItemID()
	pduo.mutation.SetItemID(i)
	return pduo
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (pduo *PDFDownloadUpdateOne) SetNillableItemID(i *int) *PDFDownloadUpdateOne {
	if i != nil {
		pduo.SetItemID(*i)
	}
	return pduo
}

// AddItemID adds i to the "item_id" field.
func (pduo *PDFDownloadUpdateOne) AddItemID(i int) *PDFDownloadUpdateOne {
	pduo.mutation.AddItemID(i)
	return pduo
}

// ClearItemID clears the value of the "item_id" field.
func (pduo *PDFDownloadUpdateOne) ClearItemID() *PDFDownloadUpdateOne {
	pduo.mutation.ClearItemID()
	return pduo
}

// Mutation returns the PDFDownloadMutation object of the builder.
func (pduo *PDFDownloadUpdateOne) Mutation() *PDFDownloadMutation {
	return pduo.mutation
}

// Where appends a list predicates to the PDFDownloadUpdate builder.
func (pduo *PDFDownloadUpdateOne) Where(ps ...predicate.PDFDownload) *PDFDownloadUpdateOne {
	pduo.mutation.Where(ps...)
	return pduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pduo *PDFDownloadUpdateOne) Select(field string, fields ...string) *PDFDownloadUpdateOne {
	pduo.fields = append([]string{field}, fields...)
	return pduo
}

// Save executes the query and returns the updated PDFDownload entity.
func (pduo *PDFDownloadUpdateOne) Save(ctx context.Context) (*PDFDownload, error) {
	return withHooks(ctx, pduo.sqlSave, pduo.mutation, pduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pduo *PDFDownloadUpdateOne) SaveX(ctx context.Context) *PDFDownload {
	node, err := pduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pduo *PDFDownloadUpdateOne) Exec(ctx context.Context) error {
	_, err := pduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pduo *PDFDownloadUpdateOne) ExecX(ctx context.Context) {
	if err := pduo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pduo *PDFDownloadUpdateOne) sqlSave(ctx context.Context) (_node *PDFDownload, err error) {
	_spec := sqlgraph.NewUpdateSpec(pdfdownload.Table, pdfdownload.Columns, sqlgraph.NewFieldSpec(pdfdownload.FieldID, field.TypeInt))
	id, ok := pduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PDFDownload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pdfdownload.FieldID)
		for _, f := range fields {
			if !pdfdownload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pdfdownload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pduo.mutation.LinkID(); ok {
		_spec.SetField(pdfdownload.FieldLinkID, field.TypeString, value)
	}
	if value, ok := pduo.mutation.PdfID(); ok {
		_spec.SetField(pdfdownload.FieldPdfID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedPdfID(); ok {
		_spec.AddField(pdfdownload.FieldPdfID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.Timestamp(); ok {
		_spec.SetField(pdfdownload.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.EmailSent(); ok {
		_spec.SetField(pdfdownload.FieldEmailSent, field.TypeBool, value)
	}
	if value, ok := pduo.mutation.LastDownload(); ok {
		_spec.SetField(pdfdownload.FieldLastDownload, field.TypeTime, value)
	}
	if pduo.mutation.LastDownloadCleared() {
		_spec.ClearField(pdfdownload.FieldLastDownload, field.TypeTime)
	}
	if value, ok := pduo.mutation.DownloadCount(); ok {
		_spec.SetField(pdfdownload.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedDownloadCount(); ok {
		_spec.AddField(pdfdownload.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.OrderID(); ok {
		_spec.SetField(pdfdownload.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedOrderID(); ok {
		_spec.AddField(pdfdownload.FieldOrderID, field.TypeInt, value)
	}
	if pduo.mutation.OrderIDCleared() {
		_spec.ClearField(pdfdownload.FieldOrderID, field.TypeInt)
	}
	if value, ok := pduo.mutation.ItemID(); ok {
		_spec.SetField(pdfdownload.FieldItemID, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedItemID(); ok {
		_spec.AddField(pdfdownload.FieldItemID, field.TypeInt, value)
	}
	if pduo.mutation.ItemIDCleared() {
		_spec.ClearField(pdfdownload.FieldItemID, field.TypeInt)
	}
	_node = &PDFDownload{config: pduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pdfdownload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pduo.mutation.done = true
	return _node, nil
}
