// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/augustin-wien/augustina-backend/ent/item"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
	"github.com/augustin-wien/augustina-backend/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAGBUrl sets the "AGBUrl" field.
func (_u *SettingsUpdate) SetAGBUrl(v string) *SettingsUpdate {
	_u.mutation.SetAGBUrl(v)
	return _u
}

// SetNillableAGBUrl sets the "AGBUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableAGBUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetAGBUrl(*v)
	}
	return _u
}

// SetColor sets the "Color" field.
func (_u *SettingsUpdate) SetColor(v string) *SettingsUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "Color" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableColor(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetFontColor sets the "FontColor" field.
func (_u *SettingsUpdate) SetFontColor(v string) *SettingsUpdate {
	_u.mutation.SetFontColor(v)
	return _u
}

// SetNillableFontColor sets the "FontColor" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableFontColor(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetFontColor(*v)
	}
	return _u
}

// SetLogo sets the "Logo" field.
func (_u *SettingsUpdate) SetLogo(v string) *SettingsUpdate {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "Logo" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableLogo(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// SetMaxOrderAmount sets the "MaxOrderAmount" field.
func (_u *SettingsUpdate) SetMaxOrderAmount(v int) *SettingsUpdate {
	_u.mutation.ResetMaxOrderAmount()
	_u.mutation.SetMaxOrderAmount(v)
	return _u
}

// SetNillableMaxOrderAmount sets the "MaxOrderAmount" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableMaxOrderAmount(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetMaxOrderAmount(*v)
	}
	return _u
}

// AddMaxOrderAmount adds value to the "MaxOrderAmount" field.
func (_u *SettingsUpdate) AddMaxOrderAmount(v int) *SettingsUpdate {
	_u.mutation.AddMaxOrderAmount(v)
	return _u
}

// SetOrgaCoversTransactionCosts sets the "OrgaCoversTransactionCosts" field.
func (_u *SettingsUpdate) SetOrgaCoversTransactionCosts(v bool) *SettingsUpdate {
	_u.mutation.SetOrgaCoversTransactionCosts(v)
	return _u
}

// SetNillableOrgaCoversTransactionCosts sets the "OrgaCoversTransactionCosts" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableOrgaCoversTransactionCosts(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetOrgaCoversTransactionCosts(*v)
	}
	return _u
}

// SetWebshopIsClosed sets the "WebshopIsClosed" field.
func (_u *SettingsUpdate) SetWebshopIsClosed(v bool) *SettingsUpdate {
	_u.mutation.SetWebshopIsClosed(v)
	return _u
}

// SetNillableWebshopIsClosed sets the "WebshopIsClosed" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableWebshopIsClosed(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetWebshopIsClosed(*v)
	}
	return _u
}

// SetVendorNotFoundHelpUrl sets the "VendorNotFoundHelpUrl" field.
func (_u *SettingsUpdate) SetVendorNotFoundHelpUrl(v string) *SettingsUpdate {
	_u.mutation.SetVendorNotFoundHelpUrl(v)
	return _u
}

// SetNillableVendorNotFoundHelpUrl sets the "VendorNotFoundHelpUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableVendorNotFoundHelpUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetVendorNotFoundHelpUrl(*v)
	}
	return _u
}

// SetMaintainanceModeHelpUrl sets the "MaintainanceModeHelpUrl" field.
func (_u *SettingsUpdate) SetMaintainanceModeHelpUrl(v string) *SettingsUpdate {
	_u.mutation.SetMaintainanceModeHelpUrl(v)
	return _u
}

// SetNillableMaintainanceModeHelpUrl sets the "MaintainanceModeHelpUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableMaintainanceModeHelpUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetMaintainanceModeHelpUrl(*v)
	}
	return _u
}

// SetVendorEmailPostfix sets the "VendorEmailPostfix" field.
func (_u *SettingsUpdate) SetVendorEmailPostfix(v string) *SettingsUpdate {
	_u.mutation.SetVendorEmailPostfix(v)
	return _u
}

// SetNillableVendorEmailPostfix sets the "VendorEmailPostfix" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableVendorEmailPostfix(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetVendorEmailPostfix(*v)
	}
	return _u
}

// SetNewspaperName sets the "NewspaperName" field.
func (_u *SettingsUpdate) SetNewspaperName(v string) *SettingsUpdate {
	_u.mutation.SetNewspaperName(v)
	return _u
}

// SetNillableNewspaperName sets the "NewspaperName" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableNewspaperName(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetNewspaperName(*v)
	}
	return _u
}

// SetQRCodeUrl sets the "QRCodeUrl" field.
func (_u *SettingsUpdate) SetQRCodeUrl(v string) *SettingsUpdate {
	_u.mutation.SetQRCodeUrl(v)
	return _u
}

// SetNillableQRCodeUrl sets the "QRCodeUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableQRCodeUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetQRCodeUrl(*v)
	}
	return _u
}

// SetQRCodeLogoImgUrl sets the "QRCodeLogoImgUrl" field.
func (_u *SettingsUpdate) SetQRCodeLogoImgUrl(v string) *SettingsUpdate {
	_u.mutation.SetQRCodeLogoImgUrl(v)
	return _u
}

// SetNillableQRCodeLogoImgUrl sets the "QRCodeLogoImgUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableQRCodeLogoImgUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetQRCodeLogoImgUrl(*v)
	}
	return _u
}

// SetMapCenterLat sets the "MapCenterLat" field.
func (_u *SettingsUpdate) SetMapCenterLat(v float64) *SettingsUpdate {
	_u.mutation.ResetMapCenterLat()
	_u.mutation.SetMapCenterLat(v)
	return _u
}

// SetNillableMapCenterLat sets the "MapCenterLat" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableMapCenterLat(v *float64) *SettingsUpdate {
	if v != nil {
		_u.SetMapCenterLat(*v)
	}
	return _u
}

// AddMapCenterLat adds value to the "MapCenterLat" field.
func (_u *SettingsUpdate) AddMapCenterLat(v float64) *SettingsUpdate {
	_u.mutation.AddMapCenterLat(v)
	return _u
}

// SetMapCenterLong sets the "MapCenterLong" field.
func (_u *SettingsUpdate) SetMapCenterLong(v float64) *SettingsUpdate {
	_u.mutation.ResetMapCenterLong()
	_u.mutation.SetMapCenterLong(v)
	return _u
}

// SetNillableMapCenterLong sets the "MapCenterLong" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableMapCenterLong(v *float64) *SettingsUpdate {
	if v != nil {
		_u.SetMapCenterLong(*v)
	}
	return _u
}

// AddMapCenterLong adds value to the "MapCenterLong" field.
func (_u *SettingsUpdate) AddMapCenterLong(v float64) *SettingsUpdate {
	_u.mutation.AddMapCenterLong(v)
	return _u
}

// SetUseVendorLicenseIdInShop sets the "UseVendorLicenseIdInShop" field.
func (_u *SettingsUpdate) SetUseVendorLicenseIdInShop(v bool) *SettingsUpdate {
	_u.mutation.SetUseVendorLicenseIdInShop(v)
	return _u
}

// SetNillableUseVendorLicenseIdInShop sets the "UseVendorLicenseIdInShop" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableUseVendorLicenseIdInShop(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetUseVendorLicenseIdInShop(*v)
	}
	return _u
}

// SetFavicon sets the "Favicon" field.
func (_u *SettingsUpdate) SetFavicon(v string) *SettingsUpdate {
	_u.mutation.SetFavicon(v)
	return _u
}

// SetNillableFavicon sets the "Favicon" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableFavicon(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetFavicon(*v)
	}
	return _u
}

// SetQRCodeSettings sets the "QRCodeSettings" field.
func (_u *SettingsUpdate) SetQRCodeSettings(v string) *SettingsUpdate {
	_u.mutation.SetQRCodeSettings(v)
	return _u
}

// SetNillableQRCodeSettings sets the "QRCodeSettings" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableQRCodeSettings(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetQRCodeSettings(*v)
	}
	return _u
}

// SetQRCodeEnableLogo sets the "QRCodeEnableLogo" field.
func (_u *SettingsUpdate) SetQRCodeEnableLogo(v bool) *SettingsUpdate {
	_u.mutation.SetQRCodeEnableLogo(v)
	return _u
}

// SetNillableQRCodeEnableLogo sets the "QRCodeEnableLogo" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableQRCodeEnableLogo(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetQRCodeEnableLogo(*v)
	}
	return _u
}

// SetUseTipInsteadOfDonation sets the "UseTipInsteadOfDonation" field.
func (_u *SettingsUpdate) SetUseTipInsteadOfDonation(v bool) *SettingsUpdate {
	_u.mutation.SetUseTipInsteadOfDonation(v)
	return _u
}

// SetNillableUseTipInsteadOfDonation sets the "UseTipInsteadOfDonation" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableUseTipInsteadOfDonation(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetUseTipInsteadOfDonation(*v)
	}
	return _u
}

// SetShopLanding sets the "ShopLanding" field.
func (_u *SettingsUpdate) SetShopLanding(v bool) *SettingsUpdate {
	_u.mutation.SetShopLanding(v)
	return _u
}

// SetNillableShopLanding sets the "ShopLanding" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableShopLanding(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetShopLanding(*v)
	}
	return _u
}

// SetDigitalItemsUrl sets the "DigitalItemsUrl" field.
func (_u *SettingsUpdate) SetDigitalItemsUrl(v string) *SettingsUpdate {
	_u.mutation.SetDigitalItemsUrl(v)
	return _u
}

// SetNillableDigitalItemsUrl sets the "DigitalItemsUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableDigitalItemsUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetDigitalItemsUrl(*v)
	}
	return _u
}

// SetAbonementUrl sets the "AbonementUrl" field.
func (_u *SettingsUpdate) SetAbonementUrl(v string) *SettingsUpdate {
	_u.mutation.SetAbonementUrl(v)
	return _u
}

// SetNillableAbonementUrl sets the "AbonementUrl" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableAbonementUrl(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetAbonementUrl(*v)
	}
	return _u
}

// SetPOSEnabled sets the "POSEnabled" field.
func (_u *SettingsUpdate) SetPOSEnabled(v bool) *SettingsUpdate {
	_u.mutation.SetPOSEnabled(v)
	return _u
}

// SetNillablePOSEnabled sets the "POSEnabled" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillablePOSEnabled(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetPOSEnabled(*v)
	}
	return _u
}

// SetMainItemID sets the "MainItem" edge to the Item entity by ID.
func (_u *SettingsUpdate) SetMainItemID(id int) *SettingsUpdate {
	_u.mutation.SetMainItemID(id)
	return _u
}

// SetNillableMainItemID sets the "MainItem" edge to the Item entity by ID if the given value is not nil.
func (_u *SettingsUpdate) SetNillableMainItemID(id *int) *SettingsUpdate {
	if id != nil {
		_u = _u.SetMainItemID(*id)
	}
	return _u
}

// SetMainItem sets the "MainItem" edge to the Item entity.
func (_u *SettingsUpdate) SetMainItem(v *Item) *SettingsUpdate {
	return _u.SetMainItemID(v.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdate) Mutation() *SettingsMutation {
	return _u.mutation
}

// ClearMainItem clears the "MainItem" edge to the Item entity.
func (_u *SettingsUpdate) ClearMainItem() *SettingsUpdate {
	_u.mutation.ClearMainItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AGBUrl(); ok {
		_spec.SetField(settings.FieldAGBUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(settings.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.FontColor(); ok {
		_spec.SetField(settings.FieldFontColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(settings.FieldLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxOrderAmount(); ok {
		_spec.SetField(settings.FieldMaxOrderAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderAmount(); ok {
		_spec.AddField(settings.FieldMaxOrderAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrgaCoversTransactionCosts(); ok {
		_spec.SetField(settings.FieldOrgaCoversTransactionCosts, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebshopIsClosed(); ok {
		_spec.SetField(settings.FieldWebshopIsClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VendorNotFoundHelpUrl(); ok {
		_spec.SetField(settings.FieldVendorNotFoundHelpUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaintainanceModeHelpUrl(); ok {
		_spec.SetField(settings.FieldMaintainanceModeHelpUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.VendorEmailPostfix(); ok {
		_spec.SetField(settings.FieldVendorEmailPostfix, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewspaperName(); ok {
		_spec.SetField(settings.FieldNewspaperName, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeUrl(); ok {
		_spec.SetField(settings.FieldQRCodeUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeLogoImgUrl(); ok {
		_spec.SetField(settings.FieldQRCodeLogoImgUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.MapCenterLat(); ok {
		_spec.SetField(settings.FieldMapCenterLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMapCenterLat(); ok {
		_spec.AddField(settings.FieldMapCenterLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MapCenterLong(); ok {
		_spec.SetField(settings.FieldMapCenterLong, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMapCenterLong(); ok {
		_spec.AddField(settings.FieldMapCenterLong, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UseVendorLicenseIdInShop(); ok {
		_spec.SetField(settings.FieldUseVendorLicenseIdInShop, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Favicon(); ok {
		_spec.SetField(settings.FieldFavicon, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeSettings(); ok {
		_spec.SetField(settings.FieldQRCodeSettings, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeEnableLogo(); ok {
		_spec.SetField(settings.FieldQRCodeEnableLogo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseTipInsteadOfDonation(); ok {
		_spec.SetField(settings.FieldUseTipInsteadOfDonation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShopLanding(); ok {
		_spec.SetField(settings.FieldShopLanding, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DigitalItemsUrl(); ok {
		_spec.SetField(settings.FieldDigitalItemsUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.AbonementUrl(); ok {
		_spec.SetField(settings.FieldAbonementUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.POSEnabled(); ok {
		_spec.SetField(settings.FieldPOSEnabled, field.TypeBool, value)
	}
	if _u.mutation.MainItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.MainItemTable,
			Columns: []string{settings.MainItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.MainItemTable,
			Columns: []string{settings.MainItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetAGBUrl sets the "AGBUrl" field.
func (_u *SettingsUpdateOne) SetAGBUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetAGBUrl(v)
	return _u
}

// SetNillableAGBUrl sets the "AGBUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableAGBUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetAGBUrl(*v)
	}
	return _u
}

// SetColor sets the "Color" field.
func (_u *SettingsUpdateOne) SetColor(v string) *SettingsUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "Color" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableColor(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetFontColor sets the "FontColor" field.
func (_u *SettingsUpdateOne) SetFontColor(v string) *SettingsUpdateOne {
	_u.mutation.SetFontColor(v)
	return _u
}

// SetNillableFontColor sets the "FontColor" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableFontColor(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetFontColor(*v)
	}
	return _u
}

// SetLogo sets the "Logo" field.
func (_u *SettingsUpdateOne) SetLogo(v string) *SettingsUpdateOne {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "Logo" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableLogo(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// SetMaxOrderAmount sets the "MaxOrderAmount" field.
func (_u *SettingsUpdateOne) SetMaxOrderAmount(v int) *SettingsUpdateOne {
	_u.mutation.ResetMaxOrderAmount()
	_u.mutation.SetMaxOrderAmount(v)
	return _u
}

// SetNillableMaxOrderAmount sets the "MaxOrderAmount" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableMaxOrderAmount(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetMaxOrderAmount(*v)
	}
	return _u
}

// AddMaxOrderAmount adds value to the "MaxOrderAmount" field.
func (_u *SettingsUpdateOne) AddMaxOrderAmount(v int) *SettingsUpdateOne {
	_u.mutation.AddMaxOrderAmount(v)
	return _u
}

// SetOrgaCoversTransactionCosts sets the "OrgaCoversTransactionCosts" field.
func (_u *SettingsUpdateOne) SetOrgaCoversTransactionCosts(v bool) *SettingsUpdateOne {
	_u.mutation.SetOrgaCoversTransactionCosts(v)
	return _u
}

// SetNillableOrgaCoversTransactionCosts sets the "OrgaCoversTransactionCosts" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableOrgaCoversTransactionCosts(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetOrgaCoversTransactionCosts(*v)
	}
	return _u
}

// SetWebshopIsClosed sets the "WebshopIsClosed" field.
func (_u *SettingsUpdateOne) SetWebshopIsClosed(v bool) *SettingsUpdateOne {
	_u.mutation.SetWebshopIsClosed(v)
	return _u
}

// SetNillableWebshopIsClosed sets the "WebshopIsClosed" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableWebshopIsClosed(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetWebshopIsClosed(*v)
	}
	return _u
}

// SetVendorNotFoundHelpUrl sets the "VendorNotFoundHelpUrl" field.
func (_u *SettingsUpdateOne) SetVendorNotFoundHelpUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetVendorNotFoundHelpUrl(v)
	return _u
}

// SetNillableVendorNotFoundHelpUrl sets the "VendorNotFoundHelpUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableVendorNotFoundHelpUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetVendorNotFoundHelpUrl(*v)
	}
	return _u
}

// SetMaintainanceModeHelpUrl sets the "MaintainanceModeHelpUrl" field.
func (_u *SettingsUpdateOne) SetMaintainanceModeHelpUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetMaintainanceModeHelpUrl(v)
	return _u
}

// SetNillableMaintainanceModeHelpUrl sets the "MaintainanceModeHelpUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableMaintainanceModeHelpUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetMaintainanceModeHelpUrl(*v)
	}
	return _u
}

// SetVendorEmailPostfix sets the "VendorEmailPostfix" field.
func (_u *SettingsUpdateOne) SetVendorEmailPostfix(v string) *SettingsUpdateOne {
	_u.mutation.SetVendorEmailPostfix(v)
	return _u
}

// SetNillableVendorEmailPostfix sets the "VendorEmailPostfix" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableVendorEmailPostfix(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetVendorEmailPostfix(*v)
	}
	return _u
}

// SetNewspaperName sets the "NewspaperName" field.
func (_u *SettingsUpdateOne) SetNewspaperName(v string) *SettingsUpdateOne {
	_u.mutation.SetNewspaperName(v)
	return _u
}

// SetNillableNewspaperName sets the "NewspaperName" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableNewspaperName(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetNewspaperName(*v)
	}
	return _u
}

// SetQRCodeUrl sets the "QRCodeUrl" field.
func (_u *SettingsUpdateOne) SetQRCodeUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetQRCodeUrl(v)
	return _u
}

// SetNillableQRCodeUrl sets the "QRCodeUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableQRCodeUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetQRCodeUrl(*v)
	}
	return _u
}

// SetQRCodeLogoImgUrl sets the "QRCodeLogoImgUrl" field.
func (_u *SettingsUpdateOne) SetQRCodeLogoImgUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetQRCodeLogoImgUrl(v)
	return _u
}

// SetNillableQRCodeLogoImgUrl sets the "QRCodeLogoImgUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableQRCodeLogoImgUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetQRCodeLogoImgUrl(*v)
	}
	return _u
}

// SetMapCenterLat sets the "MapCenterLat" field.
func (_u *SettingsUpdateOne) SetMapCenterLat(v float64) *SettingsUpdateOne {
	_u.mutation.ResetMapCenterLat()
	_u.mutation.SetMapCenterLat(v)
	return _u
}

// SetNillableMapCenterLat sets the "MapCenterLat" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableMapCenterLat(v *float64) *SettingsUpdateOne {
	if v != nil {
		_u.SetMapCenterLat(*v)
	}
	return _u
}

// AddMapCenterLat adds value to the "MapCenterLat" field.
func (_u *SettingsUpdateOne) AddMapCenterLat(v float64) *SettingsUpdateOne {
	_u.mutation.AddMapCenterLat(v)
	return _u
}

// SetMapCenterLong sets the "MapCenterLong" field.
func (_u *SettingsUpdateOne) SetMapCenterLong(v float64) *SettingsUpdateOne {
	_u.mutation.ResetMapCenterLong()
	_u.mutation.SetMapCenterLong(v)
	return _u
}

// SetNillableMapCenterLong sets the "MapCenterLong" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableMapCenterLong(v *float64) *SettingsUpdateOne {
	if v != nil {
		_u.SetMapCenterLong(*v)
	}
	return _u
}

// AddMapCenterLong adds value to the "MapCenterLong" field.
func (_u *SettingsUpdateOne) AddMapCenterLong(v float64) *SettingsUpdateOne {
	_u.mutation.AddMapCenterLong(v)
	return _u
}

// SetUseVendorLicenseIdInShop sets the "UseVendorLicenseIdInShop" field.
func (_u *SettingsUpdateOne) SetUseVendorLicenseIdInShop(v bool) *SettingsUpdateOne {
	_u.mutation.SetUseVendorLicenseIdInShop(v)
	return _u
}

// SetNillableUseVendorLicenseIdInShop sets the "UseVendorLicenseIdInShop" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableUseVendorLicenseIdInShop(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetUseVendorLicenseIdInShop(*v)
	}
	return _u
}

// SetFavicon sets the "Favicon" field.
func (_u *SettingsUpdateOne) SetFavicon(v string) *SettingsUpdateOne {
	_u.mutation.SetFavicon(v)
	return _u
}

// SetNillableFavicon sets the "Favicon" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableFavicon(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetFavicon(*v)
	}
	return _u
}

// SetQRCodeSettings sets the "QRCodeSettings" field.
func (_u *SettingsUpdateOne) SetQRCodeSettings(v string) *SettingsUpdateOne {
	_u.mutation.SetQRCodeSettings(v)
	return _u
}

// SetNillableQRCodeSettings sets the "QRCodeSettings" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableQRCodeSettings(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetQRCodeSettings(*v)
	}
	return _u
}

// SetQRCodeEnableLogo sets the "QRCodeEnableLogo" field.
func (_u *SettingsUpdateOne) SetQRCodeEnableLogo(v bool) *SettingsUpdateOne {
	_u.mutation.SetQRCodeEnableLogo(v)
	return _u
}

// SetNillableQRCodeEnableLogo sets the "QRCodeEnableLogo" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableQRCodeEnableLogo(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetQRCodeEnableLogo(*v)
	}
	return _u
}

// SetUseTipInsteadOfDonation sets the "UseTipInsteadOfDonation" field.
func (_u *SettingsUpdateOne) SetUseTipInsteadOfDonation(v bool) *SettingsUpdateOne {
	_u.mutation.SetUseTipInsteadOfDonation(v)
	return _u
}

// SetNillableUseTipInsteadOfDonation sets the "UseTipInsteadOfDonation" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableUseTipInsteadOfDonation(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetUseTipInsteadOfDonation(*v)
	}
	return _u
}

// SetShopLanding sets the "ShopLanding" field.
func (_u *SettingsUpdateOne) SetShopLanding(v bool) *SettingsUpdateOne {
	_u.mutation.SetShopLanding(v)
	return _u
}

// SetNillableShopLanding sets the "ShopLanding" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableShopLanding(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetShopLanding(*v)
	}
	return _u
}

// SetDigitalItemsUrl sets the "DigitalItemsUrl" field.
func (_u *SettingsUpdateOne) SetDigitalItemsUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetDigitalItemsUrl(v)
	return _u
}

// SetNillableDigitalItemsUrl sets the "DigitalItemsUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableDigitalItemsUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetDigitalItemsUrl(*v)
	}
	return _u
}

// SetAbonementUrl sets the "AbonementUrl" field.
func (_u *SettingsUpdateOne) SetAbonementUrl(v string) *SettingsUpdateOne {
	_u.mutation.SetAbonementUrl(v)
	return _u
}

// SetNillableAbonementUrl sets the "AbonementUrl" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableAbonementUrl(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetAbonementUrl(*v)
	}
	return _u
}

// SetPOSEnabled sets the "POSEnabled" field.
func (_u *SettingsUpdateOne) SetPOSEnabled(v bool) *SettingsUpdateOne {
	_u.mutation.SetPOSEnabled(v)
	return _u
}

// SetNillablePOSEnabled sets the "POSEnabled" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillablePOSEnabled(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetPOSEnabled(*v)
	}
	return _u
}

// SetMainItemID sets the "MainItem" edge to the Item entity by ID.
func (_u *SettingsUpdateOne) SetMainItemID(id int) *SettingsUpdateOne {
	_u.mutation.SetMainItemID(id)
	return _u
}

// SetNillableMainItemID sets the "MainItem" edge to the Item entity by ID if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableMainItemID(id *int) *SettingsUpdateOne {
	if id != nil {
		_u = _u.SetMainItemID(*id)
	}
	return _u
}

// SetMainItem sets the "MainItem" edge to the Item entity.
func (_u *SettingsUpdateOne) SetMainItem(v *Item) *SettingsUpdateOne {
	return _u.SetMainItemID(v.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdateOne) Mutation() *SettingsMutation {
	return _u.mutation
}

// ClearMainItem clears the "MainItem" edge to the Item entity.
func (_u *SettingsUpdateOne) ClearMainItem() *SettingsUpdateOne {
	_u.mutation.ClearMainItem()
	return _u
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Settings entity.
func (_u *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AGBUrl(); ok {
		_spec.SetField(settings.FieldAGBUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(settings.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.FontColor(); ok {
		_spec.SetField(settings.FieldFontColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(settings.FieldLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxOrderAmount(); ok {
		_spec.SetField(settings.FieldMaxOrderAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderAmount(); ok {
		_spec.AddField(settings.FieldMaxOrderAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrgaCoversTransactionCosts(); ok {
		_spec.SetField(settings.FieldOrgaCoversTransactionCosts, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebshopIsClosed(); ok {
		_spec.SetField(settings.FieldWebshopIsClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VendorNotFoundHelpUrl(); ok {
		_spec.SetField(settings.FieldVendorNotFoundHelpUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaintainanceModeHelpUrl(); ok {
		_spec.SetField(settings.FieldMaintainanceModeHelpUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.VendorEmailPostfix(); ok {
		_spec.SetField(settings.FieldVendorEmailPostfix, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewspaperName(); ok {
		_spec.SetField(settings.FieldNewspaperName, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeUrl(); ok {
		_spec.SetField(settings.FieldQRCodeUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeLogoImgUrl(); ok {
		_spec.SetField(settings.FieldQRCodeLogoImgUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.MapCenterLat(); ok {
		_spec.SetField(settings.FieldMapCenterLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMapCenterLat(); ok {
		_spec.AddField(settings.FieldMapCenterLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MapCenterLong(); ok {
		_spec.SetField(settings.FieldMapCenterLong, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMapCenterLong(); ok {
		_spec.AddField(settings.FieldMapCenterLong, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UseVendorLicenseIdInShop(); ok {
		_spec.SetField(settings.FieldUseVendorLicenseIdInShop, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Favicon(); ok {
		_spec.SetField(settings.FieldFavicon, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeSettings(); ok {
		_spec.SetField(settings.FieldQRCodeSettings, field.TypeString, value)
	}
	if value, ok := _u.mutation.QRCodeEnableLogo(); ok {
		_spec.SetField(settings.FieldQRCodeEnableLogo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseTipInsteadOfDonation(); ok {
		_spec.SetField(settings.FieldUseTipInsteadOfDonation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShopLanding(); ok {
		_spec.SetField(settings.FieldShopLanding, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DigitalItemsUrl(); ok {
		_spec.SetField(settings.FieldDigitalItemsUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.AbonementUrl(); ok {
		_spec.SetField(settings.FieldAbonementUrl, field.TypeString, value)
	}
	if value, ok := _u.mutation.POSEnabled(); ok {
		_spec.SetField(settings.FieldPOSEnabled, field.TypeBool, value)
	}
	if _u.mutation.MainItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.MainItemTable,
			Columns: []string{settings.MainItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.MainItemTable,
			Columns: []string{settings.MainItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Settings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
