ALTER TABLE vendor
    ADD COLUMN IF NOT EXISTS isblocked BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS blockednote TEXT NOT NULL DEFAULT '';

ALTER TABLE locations
    ADD COLUMN IF NOT EXISTS telephone TEXT NOT NULL DEFAULT '';
