// Code generated by ent, DO NOT EDIT.

package pdfdownload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldID, id))
}

// LinkID applies equality check predicate on the "link_id" field. It's identical to LinkIDEQ.
func LinkID(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldLinkID, v))
}

// PdfID applies equality check predicate on the "pdf_id" field. It's identical to PdfIDEQ.
func PdfID(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldPdfID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldTimestamp, v))
}

// EmailSent applies equality check predicate on the "email_sent" field. It's identical to EmailSentEQ.
func EmailSent(v bool) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldEmailSent, v))
}

// LastDownload applies equality check predicate on the "last_download" field. It's identical to LastDownloadEQ.
func LastDownload(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldLastDownload, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldDownloadCount, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldOrderID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldItemID, v))
}

// LinkIDEQ applies the EQ predicate on the "link_id" field.
func LinkIDEQ(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldLinkID, v))
}

// LinkIDNEQ applies the NEQ predicate on the "link_id" field.
func LinkIDNEQ(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldLinkID, v))
}

// LinkIDIn applies the In predicate on the "link_id" field.
func LinkIDIn(vs ...string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldLinkID, vs...))
}

// LinkIDNotIn applies the NotIn predicate on the "link_id" field.
func LinkIDNotIn(vs ...string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldLinkID, vs...))
}

// LinkIDGT applies the GT predicate on the "link_id" field.
func LinkIDGT(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldLinkID, v))
}

// LinkIDGTE applies the GTE predicate on the "link_id" field.
func LinkIDGTE(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldLinkID, v))
}

// LinkIDLT applies the LT predicate on the "link_id" field.
func LinkIDLT(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldLinkID, v))
}

// LinkIDLTE applies the LTE predicate on the "link_id" field.
func LinkIDLTE(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldLinkID, v))
}

// LinkIDContains applies the Contains predicate on the "link_id" field.
func LinkIDContains(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldContains(FieldLinkID, v))
}

// LinkIDHasPrefix applies the HasPrefix predicate on the "link_id" field.
func LinkIDHasPrefix(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldHasPrefix(FieldLinkID, v))
}

// LinkIDHasSuffix applies the HasSuffix predicate on the "link_id" field.
func LinkIDHasSuffix(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldHasSuffix(FieldLinkID, v))
}

// LinkIDEqualFold applies the EqualFold predicate on the "link_id" field.
func LinkIDEqualFold(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEqualFold(FieldLinkID, v))
}

// LinkIDContainsFold applies the ContainsFold predicate on the "link_id" field.
func LinkIDContainsFold(v string) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldContainsFold(FieldLinkID, v))
}

// PdfIDEQ applies the EQ predicate on the "pdf_id" field.
func PdfIDEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldPdfID, v))
}

// PdfIDNEQ applies the NEQ predicate on the "pdf_id" field.
func PdfIDNEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldPdfID, v))
}

// PdfIDIn applies the In predicate on the "pdf_id" field.
func PdfIDIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldPdfID, vs...))
}

// PdfIDNotIn applies the NotIn predicate on the "pdf_id" field.
func PdfIDNotIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldPdfID, vs...))
}

// PdfIDGT applies the GT predicate on the "pdf_id" field.
func PdfIDGT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldPdfID, v))
}

// PdfIDGTE applies the GTE predicate on the "pdf_id" field.
func PdfIDGTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldPdfID, v))
}

// PdfIDLT applies the LT predicate on the "pdf_id" field.
func PdfIDLT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldPdfID, v))
}

// PdfIDLTE applies the LTE predicate on the "pdf_id" field.
func PdfIDLTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldPdfID, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldTimestamp, v))
}

// EmailSentEQ applies the EQ predicate on the "email_sent" field.
func EmailSentEQ(v bool) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldEmailSent, v))
}

// EmailSentNEQ applies the NEQ predicate on the "email_sent" field.
func EmailSentNEQ(v bool) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldEmailSent, v))
}

// LastDownloadEQ applies the EQ predicate on the "last_download" field.
func LastDownloadEQ(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldLastDownload, v))
}

// LastDownloadNEQ applies the NEQ predicate on the "last_download" field.
func LastDownloadNEQ(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldLastDownload, v))
}

// LastDownloadIn applies the In predicate on the "last_download" field.
func LastDownloadIn(vs ...time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldLastDownload, vs...))
}

// LastDownloadNotIn applies the NotIn predicate on the "last_download" field.
func LastDownloadNotIn(vs ...time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldLastDownload, vs...))
}

// LastDownloadGT applies the GT predicate on the "last_download" field.
func LastDownloadGT(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldLastDownload, v))
}

// LastDownloadGTE applies the GTE predicate on the "last_download" field.
func LastDownloadGTE(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldLastDownload, v))
}

// LastDownloadLT applies the LT predicate on the "last_download" field.
func LastDownloadLT(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldLastDownload, v))
}

// LastDownloadLTE applies the LTE predicate on the "last_download" field.
func LastDownloadLTE(v time.Time) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldLastDownload, v))
}

// LastDownloadIsNil applies the IsNil predicate on the "last_download" field.
func LastDownloadIsNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIsNull(FieldLastDownload))
}

// LastDownloadNotNil applies the NotNil predicate on the "last_download" field.
func LastDownloadNotNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotNull(FieldLastDownload))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldDownloadCount, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotNull(FieldOrderID))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v int) predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldLTE(FieldItemID, v))
}

// ItemIDIsNil applies the IsNil predicate on the "item_id" field.
func ItemIDIsNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldIsNull(FieldItemID))
}

// ItemIDNotNil applies the NotNil predicate on the "item_id" field.
func ItemIDNotNil() predicate.PDFDownload {
	return predicate.PDFDownload(sql.FieldNotNull(FieldItemID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PDFDownload) predicate.PDFDownload {
	return predicate.PDFDownload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PDFDownload) predicate.PDFDownload {
	return predicate.PDFDownload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PDFDownload) predicate.PDFDownload {
	return predicate.PDFDownload(sql.NotPredicates(p))
}
