// Code generated by ent, DO NOT EDIT.

package workingtime

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/augustin-wien/augustina-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLTE(FieldID, id))
}

// OpenTime applies equality check predicate on the "open_time" field. It's identical to OpenTimeEQ.
func OpenTime(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldOpenTime, v))
}

// CloseTime applies equality check predicate on the "close_time" field. It's identical to CloseTimeEQ.
func CloseTime(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldCloseTime, v))
}

// Closed applies equality check predicate on the "closed" field. It's identical to ClosedEQ.
func Closed(v bool) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldClosed, v))
}

// DayEQ applies the EQ predicate on the "day" field.
func DayEQ(v Day) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldDay, v))
}

// DayNEQ applies the NEQ predicate on the "day" field.
func DayNEQ(v Day) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNEQ(FieldDay, v))
}

// DayIn applies the In predicate on the "day" field.
func DayIn(vs ...Day) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIn(FieldDay, vs...))
}

// DayNotIn applies the NotIn predicate on the "day" field.
func DayNotIn(vs ...Day) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotIn(FieldDay, vs...))
}

// OpenTimeEQ applies the EQ predicate on the "open_time" field.
func OpenTimeEQ(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldOpenTime, v))
}

// OpenTimeNEQ applies the NEQ predicate on the "open_time" field.
func OpenTimeNEQ(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNEQ(FieldOpenTime, v))
}

// OpenTimeIn applies the In predicate on the "open_time" field.
func OpenTimeIn(vs ...string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIn(FieldOpenTime, vs...))
}

// OpenTimeNotIn applies the NotIn predicate on the "open_time" field.
func OpenTimeNotIn(vs ...string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotIn(FieldOpenTime, vs...))
}

// OpenTimeGT applies the GT predicate on the "open_time" field.
func OpenTimeGT(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGT(FieldOpenTime, v))
}

// OpenTimeGTE applies the GTE predicate on the "open_time" field.
func OpenTimeGTE(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGTE(FieldOpenTime, v))
}

// OpenTimeLT applies the LT predicate on the "open_time" field.
func OpenTimeLT(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLT(FieldOpenTime, v))
}

// OpenTimeLTE applies the LTE predicate on the "open_time" field.
func OpenTimeLTE(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLTE(FieldOpenTime, v))
}

// OpenTimeContains applies the Contains predicate on the "open_time" field.
func OpenTimeContains(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldContains(FieldOpenTime, v))
}

// OpenTimeHasPrefix applies the HasPrefix predicate on the "open_time" field.
func OpenTimeHasPrefix(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldHasPrefix(FieldOpenTime, v))
}

// OpenTimeHasSuffix applies the HasSuffix predicate on the "open_time" field.
func OpenTimeHasSuffix(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldHasSuffix(FieldOpenTime, v))
}

// OpenTimeIsNil applies the IsNil predicate on the "open_time" field.
func OpenTimeIsNil() predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIsNull(FieldOpenTime))
}

// OpenTimeNotNil applies the NotNil predicate on the "open_time" field.
func OpenTimeNotNil() predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotNull(FieldOpenTime))
}

// OpenTimeEqualFold applies the EqualFold predicate on the "open_time" field.
func OpenTimeEqualFold(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEqualFold(FieldOpenTime, v))
}

// OpenTimeContainsFold applies the ContainsFold predicate on the "open_time" field.
func OpenTimeContainsFold(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldContainsFold(FieldOpenTime, v))
}

// CloseTimeEQ applies the EQ predicate on the "close_time" field.
func CloseTimeEQ(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldCloseTime, v))
}

// CloseTimeNEQ applies the NEQ predicate on the "close_time" field.
func CloseTimeNEQ(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNEQ(FieldCloseTime, v))
}

// CloseTimeIn applies the In predicate on the "close_time" field.
func CloseTimeIn(vs ...string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIn(FieldCloseTime, vs...))
}

// CloseTimeNotIn applies the NotIn predicate on the "close_time" field.
func CloseTimeNotIn(vs ...string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotIn(FieldCloseTime, vs...))
}

// CloseTimeGT applies the GT predicate on the "close_time" field.
func CloseTimeGT(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGT(FieldCloseTime, v))
}

// CloseTimeGTE applies the GTE predicate on the "close_time" field.
func CloseTimeGTE(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldGTE(FieldCloseTime, v))
}

// CloseTimeLT applies the LT predicate on the "close_time" field.
func CloseTimeLT(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLT(FieldCloseTime, v))
}

// CloseTimeLTE applies the LTE predicate on the "close_time" field.
func CloseTimeLTE(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldLTE(FieldCloseTime, v))
}

// CloseTimeContains applies the Contains predicate on the "close_time" field.
func CloseTimeContains(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldContains(FieldCloseTime, v))
}

// CloseTimeHasPrefix applies the HasPrefix predicate on the "close_time" field.
func CloseTimeHasPrefix(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldHasPrefix(FieldCloseTime, v))
}

// CloseTimeHasSuffix applies the HasSuffix predicate on the "close_time" field.
func CloseTimeHasSuffix(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldHasSuffix(FieldCloseTime, v))
}

// CloseTimeIsNil applies the IsNil predicate on the "close_time" field.
func CloseTimeIsNil() predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldIsNull(FieldCloseTime))
}

// CloseTimeNotNil applies the NotNil predicate on the "close_time" field.
func CloseTimeNotNil() predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNotNull(FieldCloseTime))
}

// CloseTimeEqualFold applies the EqualFold predicate on the "close_time" field.
func CloseTimeEqualFold(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEqualFold(FieldCloseTime, v))
}

// CloseTimeContainsFold applies the ContainsFold predicate on the "close_time" field.
func CloseTimeContainsFold(v string) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldContainsFold(FieldCloseTime, v))
}

// ClosedEQ applies the EQ predicate on the "closed" field.
func ClosedEQ(v bool) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldEQ(FieldClosed, v))
}

// ClosedNEQ applies the NEQ predicate on the "closed" field.
func ClosedNEQ(v bool) predicate.WorkingTime {
	return predicate.WorkingTime(sql.FieldNEQ(FieldClosed, v))
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.WorkingTime {
	return predicate.WorkingTime(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.WorkingTime {
	return predicate.WorkingTime(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkingTime) predicate.WorkingTime {
	return predicate.WorkingTime(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkingTime) predicate.WorkingTime {
	return predicate.WorkingTime(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkingTime) predicate.WorkingTime {
	return predicate.WorkingTime(sql.NotPredicates(p))
}
