"""
Run via `manage.py shell` by the glitchtip-init service. Idempotent: safe to
re-run on every `docker compose up`. Creates an owner account, organization,
team and project so Glitchtip is immediately usable, then writes the
resulting DSNs to dsn.env next to this file.
"""

import os

from django.apps import apps
from django.contrib.auth import get_user_model

User = get_user_model()
Organization = apps.get_model("organizations_ext", "Organization")
OrganizationUser = apps.get_model("organizations_ext", "OrganizationUser")
Team = apps.get_model("teams", "Team")
Project = apps.get_model("projects", "Project")
ProjectKey = apps.get_model("projects", "ProjectKey")

email = os.environ["GLITCHTIP_ADMIN_EMAIL"]
password = os.environ["GLITCHTIP_ADMIN_PASSWORD"]
org_name = os.environ.get("GLITCHTIP_ORG_NAME", "Augustin")
project_name = os.environ.get("GLITCHTIP_PROJECT_NAME", "augustin")
team_slug = os.environ.get("GLITCHTIP_TEAM_SLUG", "engineering")

user = User.objects.filter(email=email).first()
if user is None:
    user = User.objects.create_superuser(email=email, password=password)
    print(f"glitchtip-init: created superuser {email}")
else:
    print(f"glitchtip-init: superuser {email} already exists")

org, org_created = Organization.objects.get_or_create(name=org_name)
print(f"glitchtip-init: {'created' if org_created else 'found'} organization {org_name}")

org_user = OrganizationUser.objects.filter(organization=org, user=user).first()
if org_user is None:
    org_user = org.add_user(user)
    print(f"glitchtip-init: added {email} to {org_name}")

team, team_created = Team.objects.get_or_create(slug=team_slug, organization=org)
team.members.add(org_user)
print(f"glitchtip-init: {'created' if team_created else 'found'} team {team_slug}")

project, project_created = Project.objects.get_or_create(
    name=project_name, organization=org
)
team.projects.add(project)
print(f"glitchtip-init: {'created' if project_created else 'found'} project {project_name}")

signal_sender = os.environ.get("SIGNAL_SENDER_NUMBER", "").strip()
signal_recipients = os.environ.get("SIGNAL_RECIPIENTS", "").strip()
if signal_sender and signal_recipients:
    ProjectAlert = apps.get_model("alerts", "ProjectAlert")
    AlertRecipient = apps.get_model("alerts", "AlertRecipient")

    alert, alert_created = ProjectAlert.objects.get_or_create(
        project=project,
        name="Signal",
        defaults={"timespan_minutes": 1, "quantity": 1},
    )
    print(f"glitchtip-init: {'created' if alert_created else 'found'} Signal alert")

    _, recipient_created = AlertRecipient.objects.get_or_create(
        alert=alert,
        recipient_type="webhook",
        url="http://glitchtip-signal-relay:8080/webhook",
    )
    print(
        f"glitchtip-init: {'created' if recipient_created else 'found'} "
        "Signal alert webhook recipient"
    )
else:
    print(
        "glitchtip-init: SIGNAL_SENDER_NUMBER/SIGNAL_RECIPIENTS not set, "
        "skipping Signal alert"
    )

key = ProjectKey.objects.filter(project=project).first()
backend_dsn = f"http://{key.public_key_hex}@glitchtip-web:8000/{project.id}"
frontend_dsn = f"http://{key.public_key_hex}@localhost:8094/{project.id}"

dsn_env = (
    "# Generated by glitchtip-init on every `docker compose up`.\n"
    "# Copy these into .env to switch on error tracking.\n"
    f"SENTRY_DSN={backend_dsn}\n"
    f"VITE_SENTRY_DSN={frontend_dsn}\n"
)
with open("/glitchtip-local/dsn.env", "w") as f:
    f.write(dsn_env)

print("glitchtip-init: wrote docker/glitchtip/dsn.env")
print(dsn_env)
